### ISSUE TITLE
ConsoleReporter screenshot outdated

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#1011]
**Describe the bug**
ConsoleReporter screenshot used is outdated. Missed `Mode` column

**Expected behavior**
See a fresh version that reflect current ConsoleReporter output 

**Screenshots**
https://github.com/megalinter/megalinter/blob/main/docs/assets/images/ConsoleReporter.jpg

**Comment by nvuillam** [comment]
Agreed :)
wanna make a PR ? ^^
