### ISSUE TITLE
`report` folder is not clean-up between multiple runs

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#1012]
**Describe the bug**
When you run Mega-Linter more than one times, and fixes some linters issues between each run, the `report` folder still contains old `linters_logs` files
See screenshot with ERROR-PHP_PHPCS.log file still present, while issue was fixed in previous run!

**Expected behavior**
A `report` folder with files that contains only current logs run

**Screenshots**
![report_folder](https://user-images.githubusercontent.com/364342/142755472-04954a69-e0f2-4de5-b46d-ae5585735e98.png)

**Additional context**
Use Mega-Linter v5.1.0

**Comment by nvuillam** [comment]
As MegaLinter was initially planned to be just a CI tool, I agree that report folder can quickly become a mess locally...
Instead of cleaning, maybe do something like testing CI env var, and if yes do something like the following ?
- report
  - 2021-11-21-08-02
  - 2021-11-21-09-15
  - 2021-11-22-013-22

**Comment by llaville** [comment]
No need to make it an gaz machine ;-) I just want to keep you aware. Almost all times, I run `sudo rm -rf report/` before. But it's a pain for local developers that don't have local admin rights on their computers (I saw it in past !)

**Comment by nvuillam** [comment]
I'm afraid that for some case when there is already a report folder used by
other apps, if will also empty it, i'm afraid it's not good ^^

Maybe empty it depending on a config variable ?

Le dim. 21 nov. 2021 à 10:43, Laurent Laville ***@***.***> a
écrit :
