### ISSUE TITLE
yamllint is very slow when creating [Text Reporter] Generated TEXT report

### ISSUE THREAD

**Issue by sbollap1** [megalinter/megalinter#1020]
![Yamllint_2021_11_22](https://user-images.githubusercontent.com/4892241/142935437-bd25647b-5535-44af-ab93-56d638599b84.png)

When I am running the megalinter, and specifically running yaml linter, its very slow at the point of creating the log. I tried to disable YAML_PRETTIER, like this inside .mega-linter.yml file but thats just causing it to slow the yamllint  ([31m❌ Linted [YAML] files with [yamllint]: Found 1 error(s) - (0.86s)[0m
) now.

```
ENABLE_LINTERS: [YAML_YAMLLINT, YAML_V8R]
DISABLE_LINTERS: [GROOVY_NPM_GROOVY_LINT, YAML_PRETTIER, ENV_DOTENV_LINTER, DOCKERFILE_DOCKERFILELINT, DOCKERFILE_HADOLINT, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER]
```

**Comment by nvuillam** [comment]
I don't see how Text Reporter could be so long, as it just reads linter run info & logs and generate text files :)

But v8r can be very time consuming, as it is called for every single YAML file, do you have a lot of YML files in your repo ?

**Comment by nvuillam** [comment]
Ex with own MegaLinter linting: 
![image](https://user-images.githubusercontent.com/17500430/142942825-724b7d13-0acf-45c0-8e93-efc3c89f328e.png)

**Comment by sbollap1** [comment]
My numbers are like this:
![image](https://user-images.githubusercontent.com/4892241/142942896-6a711132-622a-4b45-b353-294d447ebef0.png)

**Comment by nvuillam** [comment]
wow !
With 22 files... i'm surprised :o 

Do you have super heavy YAML files of several megas / gigas ?

**Comment by sbollap1** [comment]
I don't see those files being really huge, 100 lines may be , total size is 80KB. I ran this locally using docker run and its faster.could it be because i am running this on jenkins as part of a pipeline
![image](https://user-images.githubusercontent.com/4892241/142943671-61abc9ea-ef16-4ab5-81eb-e286241775e5.png)

**Comment by nvuillam** [comment]
I confirm that such huge execution time should not happen 
And it's even stranger if locally

what if you run `npx mega-linter-runner@beta` at the root of your repo ? It's what should be closed to the run from Jenkins

Maybe you can share the part of your jenkinsfile running MegaLinter + your `.mega-linter.yml` config file ?

**Comment by sbollap1** [comment]
```
GROOVY_NPM_GROOVY_LINT_ARGUMENTS: "--failon warning"
FILTER_REGEX_EXCLUDE: (src/|vars/)
ENABLE_LINTERS: [YAML_YAMLLINT, YAML_PRETTIER]
DISABLE_LINTERS: [GROOVY_NPM_GROOVY_LINT, YAML_V8R, ENV_DOTENV_LINTER, DOCKERFILE_DOCKERFILELINT, DOCKERFILE_HADOLINT, JSON_JSONLINT, JSON_ESLINT_PLUGIN_JSONC, JSON_V8R, JSON_PRETTIER]

```
.mega-linter.yml file is as shown above. when I disable V8R its fast. I have no control over Jenkins. I ran npx at the root of my repo, and its fine.

**Comment by appmakerusa** [comment]
I am also looking to increase MegaLinter performance speeds. I disabled YAML_PRETTIER because some of the errors it was reporting to me were minor formatting issues. I retained the other YAML linters. They were reporting SUCCESS on the same file that YAML_PRETTIER was reporting ERROR.

**Comment by nvuillam** [comment]
What is your results table ? What are the linters taking a lof of time ?

**Comment by sbollap1** [comment]
@nvuillam i have something like this in .mega-linter.yml file to run the lint only on one file. to fix issues. this is the workaround if you will to not check all the ~400 groovy that I have which is time consuming.

```
GROOVY_NPM_GROOVY_LINT_ARGUMENTS: "--failon warning"
FILTER_REGEX_EXCLUDE: (mysrc/|mydir/)
FILTER_REGEX_INCLUDE: hw/seed.groovy
DISABLE_LINTERS:
   - JSON_PRETTIER
   - DOCKERFILE_DOCKERFILELINT
   - JSON_JSONLINT
   - JSON_ESLINT_PLUGIN_JSONC
   - YAML_YAMLLINT
   - YAML_V8R
   - ENV_DOTENV_LINTER
   - YAML_PRETTIER
   - JSON_V8R

```
separate question, however. is
and inside the .groovylintrc file i have the following, is there a rule i can add in this file to see the duplicate code, i am trying to see if there is a rule like that

```
{
    "extends": "recommended",
    "rules": {
        "CatchException": {
            "enabled": false
        },
        "CatchThrowable": {
            "enabled": false
        },
        "CompileStatic": {
            "enabled": false
        },
        "DuplicateMapLiteral": {
            "enabled": false
        },
        "DuplicateNumberLiteral": {
            "enabled": false
        },
        "DuplicateStringLiteral": {
            "enabled": false
        },
        "GStringAsMapKey": {
            "enabled": false
        },
        "Instanceof": {
            "enabled": false
        },
        "JavaIoPackageAccess": {
            "enabled": false
        },
        "LineLength": {
            "enabled": false
        },
        "MethodName": {
            "enabled": false
        },
        "NestedBlockDepth": {
            "enabled": false
        },
        "NoDouble": {
            "enabled": false
        },
        "NoFloat": {
            "enabled": false
        },
        "NoJavaUtilDate": {
            "enabled": false
        },
        "ParameterName": {
            "enabled": false
        },
        "VariableName": {
            "enabled": false
        }
    }
}
```

**Comment by nvuillam** [comment]
Try `FILTER_REGEX_INCLUDE: (hw\/seed\.groovy)` :)

https://regex101.com/r/3v0NOY/1/

**Comment by sbollap1** [comment]
@nvuillam my question was regarding setting the rule to find duplicate code, thanks for the above tip though
