### ISSUE TITLE
Add `phplint` to speed-up linting of php files

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#1031]
Even if PHP built-in linter is pretty fast, it suffer a main default : it must call only one time by identified file (only `file` mode supported).

After some tries as a plugin (see #1027), it's time now to include https://github.com/overtrue/phplint as an official PHP linter.

Enhancement vs PHP built-in 
- support all modes (`project`, `list_of_files`,  `file`)
- more faster

Here is a real life usage obtained with  https://github.com/llaville/php-compatinfo-db source files (more than 200 php files)

With `list_of_files` mode and default `phplint` behaviors (5 lint jobs run in parallel, and file caching result usage)

![phplint_ml_plugin](https://user-images.githubusercontent.com/364342/143560314-34f15547-b3a4-45a3-85e7-0eff2fdc2ded.png)

8 times faster than PHP 7.4 built-in

**Comment by nvuillam** [comment]
That's great :)
Does it mean that we can get rid of native php linter, if it tracks exactly the same errors ? :)

**Comment by llaville** [comment]
Not exactly, because as I said, the performance may be worst than native php linter when there are few php files to scan. I don't know yet the limit when performance are down.
But `phplint` detect of course the same errors (launch multiple jobs `php -l` in parallel)

**Comment by nvuillam** [comment]
I think we can assume that there will be more cases with a lot of PHP files, so let's get rid of PHP native linter if we add phplint ? :)

**Comment by llaville** [comment]
Wait at least a new MegaLinter version cycle before decide to remove native PHP built-in linter

**Comment by llaville** [comment]
After some tests, I can tell : 
- PHP 7.4 built-in linter is better than `phplint` when you've less than 30 files to scan
- `phplint` is then become better when you've more than 30 files

**Comment by llaville** [comment]
As this new linter use massive usage of `docker run` commands, I recommend to wait that issue #1033 is solved

**Comment by nvuillam** [comment]
@llaville the CI error is caused by the fact that the test method that is supposed the detect errors in PHP bad files .. finds no error ^^

![image](https://user-images.githubusercontent.com/17500430/143691328-d34b100a-6a5f-4c3d-a77e-952fef35509e.png)

**Comment by llaville** [comment]
@nvuillam My surprise is to see the PHP warning that not found the config file, while default template exists TEMPLATES/.phplint.yml
Any idea ?

**Comment by llaville** [comment]
@nvuillam With a "night's repair", I've finally understood. Mega-Linter `docker run` context need some fixes ...

**Comment by llaville** [comment]
I won't keep dind install, because it suffer from a performance issue when there are few php files to scan. 
I'll use composer global install that fix all problems, including performance issues. In all case `phplint` is better than native PHP built-in linter even for few files ( < 10 ).

**Comment by llaville** [comment]
Here are some performance results (with composer global install process)

![phplint_vs_php-l__15](https://user-images.githubusercontent.com/364342/143780019-fec3e0f0-fb43-495b-a2a1-cd0bbbb7e94b.png)

![phplint_vs_php-l__223](https://user-images.githubusercontent.com/364342/143780030-09d1ebbe-3894-4010-97f0-3a1dd64dfd51.png)
