### ISSUE TITLE
Add fish shell linter/formatter

### ISSUE THREAD

**Issue by IlanCosman** [megalinter/megalinter#1039]
The Fish shell has an official formatter, [`fish_indent`](https://fishshell.com/docs/current/cmds/fish_indent.html). Source code can be found at https://github.com/fish-shell/fish-shell/blob/master/src/fish_indent.cpp. 

Could this be added to mega linter?

**Comment by nvuillam** [comment]
This cold be nice yes :)
- It is callable from bash ?
- Is there a --check way to call it, for users without APPLY_FIXES ?
- Do you have installation info on alpine linux ? (I see all distros but not alpine on https://fishshell.com/ )

**Comment by IlanCosman** [comment]
- Yes, fish_indent is it's own binary.
- Yes, it has a `--check` option
- Yes, alpine has fish in it's main repositories. https://pkgs.alpinelinux.org/package/edge/main/x86/fish

I'm not sure if it's possible to just get fish_indent though, without installing fish. And I'm not sure if you'd want to install the whole shell. Though that would give the bonus of adding basic fish linting with `fish --no-execute`.

**Comment by nvuillam** [comment]
Ok, i'll have a look when I'll have time, or you can try to make a PR :)

https://megalinter.github.io/latest/contributing/#add-a-new-linter
