### ISSUE TITLE
`phplint` documentation does not reflect descriptor file

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#1048]
**Describe the bug**
By reading new `phplint` linter documentation at https://megalinter.github.io/beta/descriptors/php_phplint/, I've noticed that dockerfile commands did not reflect contents of php descriptor file https://github.com/megalinter/megalinter/blob/adfd1bad313629b80db2f87a46b9ac7769c3aefc/megalinter/descriptors/php.megalinter-descriptor.yml#L163-L168

**Expected behavior**
Only see commands that are defined in php descriptor yaml file, and not commands related to phive installation unless its not possible

**Screenshots**
![megalinter github io_beta_descriptors_php_phplint](https://user-images.githubusercontent.com/364342/144009665-f8b3990b-cfc0-4662-99aa-bec0a53bdf45.png)

**Comment by nvuillam** [comment]
When you run `bash build.sh` without --doc (and it's a good idea to avoid conflicts with other PRs), documentation is not updated.
But daily auto-updater takes care of that :) ( https://github.com/megalinter/megalinter/pull/1046 )

CI failed yesterday but as soon at it will pass, it will be updated :)
