### ISSUE TITLE
Base Image Missing    Base images should specify a tag to use

### ISSUE THREAD

**Issue by sbollap1** [megalinter/megalinter#1053]
I am seeing this issue when lint is being run on my Dockerfile(s). How can I disable this specific error. during linting DOCKERFILE_DOCKERFILELINT is the linter being used
```
Line 3: FROM ${FROM}
Issue  Category      Title                 Description
    1  Clarity       Base Image Missing    Base images should specify a tag to use.
                     Tag
```
My dockerfile is looking like this:
```

ARG FROM=docker.io/ubuntu:bionic

FROM ${FROM}

ARG URL=https://pypi.python.org/simple/
...

```

Currently, my .dockerfilelintrc has this:

```
rules:
  from_first: off
```
not sure which one of these would be required  [https://github.com/replicatedhq/dockerfilelint](https://github.com/replicatedhq/dockerfilelint)

**Comment by nvuillam** [comment]
@sbollap1 it seems dockerfilelint is not maintained anymore, it's possible that we remve it in next major version, as hadolint covers all its rules, so you may anticipate and add the following in your **.mega-linter.yml** file

```
DISABLE_LINTERS:
- DOCKERFILE_DOCKERFILELINT
```
