### ISSUE TITLE
Automatically apply formatting and fixes in your files

### ISSUE THREAD

**Issue by appmakerusa** [megalinter/megalinter#1064]
It seems that --fix automatically applies fixes for all errors found for all languages/formats/code quality. It would be a nice feature if we could fine tune the fixes applied. For instance, in a codeset that contains multiple languages, ie Python and C#, fixes could be automated for Python, but not for C#.  Or for even more specific, within the Python language, fixes could be automated for  PYTHON_BLACK, but not for PYTHON_ISORT.

**Comment by nvuillam** [comment]
You can already do that :)

https://megalinter.github.io/v6-alpha/configuration/#apply-fixes

For example, define in your `.mega-linter.yml` config file:

```yaml
APPLY_FIXES:
  - JAVASCRIPT_ES
  - PYTHON_BLACK
```

But I could enhance JSON schema so auto completion would be active to select linters :)

**Comment by appmakerusa** [comment]
Terrific! Thanks for the info and the quick reply.
