### ISSUE TITLE
[v6-alpha] Gitleaks version not displayed

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#1066]
**Describe the bug**
gitleaks version is not display in ConsoleReporter

**Expected behavior**
Current version 8.1.0 displayed

**Screenshots**

![github com_megalinter_megalinter_runs_4414528099_check_suite_focus=true](https://user-images.githubusercontent.com/364342/144699126-9bf6774b-3c48-4e86-ad25-400ba0d305d9.png)

Extracted from https://github.com/megalinter/megalinter/runs/4414528099?check_suite_focus=true#step:4:1017

**Comment by llaville** [comment]
Take care that gitleaks use a `version` command and not the default `--version` option MegaLinter used for all its linters.

**Comment by llaville** [comment]
Tested with latest docker image: 

![gitleaks_version](https://user-images.githubusercontent.com/364342/144699385-3c278d5a-c2b9-46fb-94c9-98b3d90c3837.png)

**Comment by nvuillam** [comment]
I had a strange bug doing that... that's why I forced it to hardcoded value, but I will try again :)
