### ISSUE TITLE
Enhance CI performance -- Build docker images with BuildKit

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#1076]
If you want to improve elapsed time on docker images built, consider to activate [BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/)

From sequential tasks to parallel tasks (depending of CPU/threads available)

i.e, what the UI look like (time elapsed displayed on right side, in real time, ...)

![megalinter_docker_buildkit](https://user-images.githubusercontent.com/364342/144800476-2be48191-9489-44a8-b31b-84f8e6aa5c07.png)

**Comment by llaville** [comment]
* Here are some screenshots taken from my laptop, that could provided ideas for improvement (tasks with lot of time elapsed)

38,5 minutes (2300 s) to build all flavors docker image


![buildkit_1](https://user-images.githubusercontent.com/364342/144805027-d9eb272c-d41f-4215-9421-76d5b1649fda.png)
![buildkit_2](https://user-images.githubusercontent.com/364342/144805040-1ee57789-18f1-45e8-8112-c4f8f27656f0.png)
![buildkit_3](https://user-images.githubusercontent.com/364342/144805060-4fb14d3c-5fb5-45ff-95d7-5fadf4a135b6.png)

**Comment by nvuillam** [comment]
38mn is similar to the current build time on GHA workflows, but let's try it in a PR :)

**Comment by llaville** [comment]
When cache option is kept, building docker image is more efficient for next runs. See in screenshots

I know we are in CI context, but when you build all flavors, I think it may help to build faster.

![buildkit_1](https://user-images.githubusercontent.com/364342/144819214-3d16f778-d6fb-4183-aad4-4940269562ef.png)
![buildkit_2](https://user-images.githubusercontent.com/364342/144819233-5d23a597-6a83-4087-860b-976a76247ee4.png)
![buildkit_3](https://user-images.githubusercontent.com/364342/144819253-bf522ee7-b9d6-482d-8859-94d87eb6d2bb.png)
