### ISSUE TITLE
Megalinter comment reporter for gerrit

### ISSUE THREAD

**Issue by sbollap1** [megalinter/megalinter#1111]
I see some configuration parameters which may be set to be able to post a comment in the github. [megalinter comment reporter](https://megalinter.github.io/latest/reporters/GitHubCommentReporter/). similarly, is there a support for posting a comment or showing the line of the error in the gerrit patchset code review

**Comment by nvuillam** [comment]
@sbollap1 it could be possible to show a comment in gerrit, with a GERRIT_COMMENT_REPORTER, following the same model than [GitHub comment reporter](https://github.com/megalinter/megalinter/blob/main/megalinter/reporters/GithubCommentReporter.py) and [Gitlab Comment Reporter](https://github.com/megalinter/megalinter/blob/main/megalinter/reporters/GitlabCommentReporter.py)

Now that both reporters exists, the building of the comment has been externalized, would you be interested to build a GerritCommentReporter.py ? 
If not, it would help me or another contributor if you provide information about how to post such comment to gerrit using gerrit api :)
