### ISSUE TITLE
Add VALIDATE_ALL_CODEBASE: false functionality for Azure Pipelines

### ISSUE THREAD

**Issue by lumarel** [megalinter/megalinter#1125]
**Is your feature request related to a problem? Please describe.**
I was currently on implementing MegaLinter on some repos on our local Azure Pipelines Server and Azure Pipelines Agents.
While testing the options, I noticed that it is not possible to use `VALIDATE_ALL_CODEBASE: false` if the Azure Pipelines Server is only available when authenticated.
This is the error, after adding the local corp certs to the certificates in the PRE_COMMANDS
```
Listing updated files in [/tmp/lint] using git diff.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 109, in run
    self.collect_files()
  File "/megalinter/MegaLinter.py", line 406, in collect_files
    all_files = self.list_files_git_diff()
  File "/megalinter/MegaLinter.py", line 509, in list_files_git_diff
    repo.git.fetch("origin", f"{remote_ref}:{local_ref}")
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 638, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 1183, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 983, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch origin HEAD:refs/remotes/origin/HEAD
  stderr: 'fatal: could not read Username for 'https://<fqdn-of-the-Azure-Pipelines-Server>': No such device or address'
```

Also added a the exact same git fetch then to the PRE_COMMANDS and that showed the login box:
```
[Pre] run: [update-ca-certificates] in cwd [/]
[Pre] [WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
[Pre] run: [git fetch origin HEAD:refs/remotes/HEAD] in cwd [/tmp/lint]
[Pre] [fatal: could not read Username for 'https://<fqdn-of-the-Azure-Pipelines-Server>': No such device or address
] fatal: could not read Username for 'https://<fqdn-of-the-Azure-Pipelines-Server>': No such device or address
```

I also definitely made sure that the server is resolvable, pingable and responds to http requests, so either I'm missing something or it really is the authentication.

**Describe the solution you'd like**
It would be great if the pipeline would work with the `VALIDATE_ALL_CODEBASE` property disabled.

**Describe alternatives you've considered**
- Running the pipeline with the before mentioned property enabled, but that takes over 16min on some repos.
- Trying to run the pipeline as if it is GitHub, with a defined environmentvariable PAT (as secret), but that didn't work

**Additional context**
The Azure Pipelines Server is an on-prem installation, the Agent runs on Linux with the Linter then as the container image.
The exact step in the pipeline is:
```
steps:
  - script: docker run -v $(System.DefaultWorkingDirectory):/tmp/lint megalinter/megalinter-dotnet:v5
    displayName: Code Scan using MegaLinter
```

If any further information is needed, I will off course try to provide it! :)

**Comment by lumarel** [comment]
Did someone already have the time to look at this? :)

**Comment by nvuillam** [comment]
I'm not familiar with Azure Pipelines, but it seems related to https://stackoverflow.com/questions/55567940/azure-pipelines-i-am-getting-fatal-could-not-read-username-for-https-github/55583374#55583374

I should be able to add `-c http.extraheader="AUTHORIZATION: bearer GIT_AUTHORIZATION_BEARER"` in git commands, would it be ok for you to define such access token in an env variable `GIT_AUTHORIZATION_BEARER` ?

**Comment by lumarel** [comment]
Thank you for looking into it even though you are not familiar with it @nvuillam!
I tried to test this method now on my end, and it looks like it works!

So yeah I'm totally fine to add the System.AccessToken as a environment variable to the Container!

Further, here are my testing steps:

Step in the Azure Pipelines config file:
```yaml
  - script: docker run -v $(System.DefaultWorkingDirectory):/tmp/lint -v $(Build.ArtifactStagingDirectory):/tmp/lint-report -e GIT_AUTHORIZATION_BEARER=$(System.AccessToken) megalinter/megalinter-dotnet:v5
    displayName: Code Scan using MegaLinter
```

and in the .mega-linter.yml:
```yaml
PRE_COMMANDS:
  - command: apk add --no-cache ca-certificates
    cwd: root
  - command: curl -L -o /usr/local/share/ca-certificates/RootCA.crt http://path.to.cert
    cwd: root
  - command: curl -L -o /usr/local/share/ca-certificates/IssueCA.crt http://path.to.cert
    cwd: root
  - command: update-ca-certificates
    cwd: root
  - command: 'git -c http.extraheader="Authorization: Bearer $GIT_AUTHORIZATION_BEARER" fetch origin HEAD:refs/remotes/HEAD'
    cwd: workspace
```

This gave me then a successful fetch!

```
2022-01-24T12:07:07.7364884Z [Pre] run: [git -c http.extraheader="Authorization: Bearer $GIT_AUTHORIZATION_BEARER" fetch origin HEAD:refs/remotes/HEAD] in cwd [/tmp/lint]
2022-01-24T12:07:07.8179679Z [Pre] [From https://<fqdn-of-the-Azure-Pipelines-Server>/path/to/repo
2022-01-24T12:07:07.8182297Z  * [new ref]                      -> HEAD
2022-01-24T12:07:07.8183679Z warning: refname 'HEAD' is ambiguous.
2022-01-24T12:07:07.8184868Z ] From https://<fqdn-of-the-Azure-Pipelines-Server>/path/to/repo
2022-01-24T12:07:07.8186256Z  * [new ref]                      -> HEAD
2022-01-24T12:07:07.8187507Z warning: refname 'HEAD' is ambiguous.
```

If you are willing to add the Authorization to the git commands, that would help a lot on my side :)
(and maybe a small docs update might be needed, so others don't have to search here)

**Comment by nvuillam** [comment]
@lumarel as I don't have ready to use Azure Pipeline poject, would you have the kindness to test my fix ? :)

- Use docker image megalinter/megalinter:test-nvuillam-git-auth
- Send GIT_AUTHORIZATION_BEARER as env variable to MegaLinter :)

**Comment by lumarel** [comment]
Yeah sure, off course I will test it for you @nvuillam :)

And yes it works flawlessly! (as long as the corp certificates are present, linked them now as the ca-certificates file from the host)

**Comment by nvuillam** [comment]
That's great, thanks for the testing,  I'll update documentation and merge the PR :)
The fix will be then available in beta version of MegaLinter, then in the next release (probably in a few days) :)

**Comment by lumarel** [comment]
Sounds great!
Thank you very much for your time :)

**Comment by nvuillam** [comment]
You're welcome :)

**Comment by nvuillam** [comment]
@lumarel I updated the documentation

https://github.com/megalinter/megalinter/blob/bugs/git-auth/README.md#azure-pipelines

I think it could be enhanced again... with stuff like 
- managing storage of artifacts ( is `-v $(Build.ArtifactStagingDirectory):/tmp/lint-report` standard ? )
- Manage to add a new commit in case APPLY_FIXES is active
- Azure PR Reporter ?

If you have ideas about enhancements or even in the code, please share them, they'll be very welcome :)

**Comment by lumarel** [comment]
@nvuillam Okay great thank you!

I don't know if the `-v $(Build.ArtifactStagingDirectory):/tmp/lint-report` is somewhat of a standard, I just wanted to keep the Git repo itself clean, because by default Azure Pipelines reuses the local Git cache on the workers, and if there is something generated inside, it fails because it doesn't want to clean it up on the next build checkout. (maybe it was because of the permissions, because the agent doesn't run with root)
Additionally adding it to the `$(Build.ArtifactStagingDirectory)` cleans it before every run and is the default directory for [Build artifactory uploads](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops-2020), which makes the report files easily accessible (there is also a PublishTestResults, but that requires a [specific folder and file structure](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml#result-formats-mapping))
Oh right you could definitely mention that here "You may activate File.io reporter or E-mail reporter to access detailed logs and fixed source"
It only needs 3 Parameters, on the pipeline side the additional volume mount, and in the MegaLinter config `REPORT_OUTPUT_FOLDER` and `COPYPASTE_JSCPD_ARGUMENTS: --output` (maybe also other linter specific configs, this was the only one where I noticed, that it doesn't follow the `REPORT_OUTPUT_FOLDER` parameter) and after finishing the Build Artifact Upload:
```yaml
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: Testrestult
  condition: always()
  displayName: Publish Testresults
```

`APPLY_FIXES` wasn't on my priority list, because I mostly lint PowerShell right now, which works great, but doesn't have the fixing function anyway ^^
But I will look into it if I have some time soon!

**Comment by nvuillam** [comment]
@lumarel thanks for all this great info, with it it seems we can clearly make azure integration as advanced as github actions or gitlab ci ones :)

**Comment by lumarel** [comment]
@nvuillam You're really welcome :)
Just had a little bit more close look, and there is definitely a API for [creating PR comments](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-thread-comments/create?view=azure-devops-server-rest-5.0) and [PRs themselves](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull-requests/create?view=azure-devops-server-rest-5.0), but that will need a seperate PAT beside the agents own token 🤔 (but at least from my side, not a priority)

**Comment by nvuillam** [comment]
If we can have the reports stored as jib artifacts by default, it would be already great because no one wants to read a 1000 lines log to check for lint errors ^^

About the future AZURE_PIPELINES_REPORTER , It seems there are api wrappers like this one https://github.com/microsoft/azure-devops-python-api , and indeed it may require a PAT like for gitlab CI... but if it is a scoped PAT it can be quite secure :)

**Comment by lumarel** [comment]
Haha yeah you're totally true, especially the PSScriptAnalyzer... Because of the docker output having a quite limited width the reports get lengthy ^^ (was already searching for ways to extend the output width)

Hm not sure if this also works for Azure DevOps Server (the On-Prem version), but definitely great that they have a prebuilt python API :)

**Comment by lumarel** [comment]
@nvuillam I just tested it now also in the megalinter:v5 tag, works like a charm!
Thank you :)

(about a AZURE_PIPELINES_REPORTER, that may be better in a separate issue, I can create one if you want ^^)

**Comment by nvuillam** [comment]
Thanks for your feedback with latest v5 version :)

agreed for the separate issue :)

**Comment by lumarel** [comment]
@nvuillam I unfortunately need to add something :)
We had an issue that the Azure DevOps server spits HTTP 400s on the next run because the linter adds the token to the `.git/config` file.
This only occurs if the repo cache is already on the agent, due to that I only noticed it so late now.
I mitigated that now for us with `sed -i '/^\s*extraheader.*$/d' $(System.DefaultWorkingDirectory)/.git/config` as a step after the linting, but maybe you have a better solution to that or want to add that somewhere to the documentation.

**Comment by nvuillam** [comment]
MegaLinter does the following code

```
        if config.get("GIT_AUTHORIZATION_BEARER", "") != "":
            auth_bearer = "Authorization: Bearer " + config.get(
                "GIT_AUTHORIZATION_BEARER"
            )
            repo.config_writer().set_value("http", "extraheader", auth_bearer).release()
```

What if I remove it after linting , with something like:

**Comment by lumarel** [comment]
Yep that would definitely help!
I unfortunately didn't notice that it configures the token repo wide and not per command, sorry

**Comment by nvuillam** [comment]
@lumarel I tried a fix, please could you test with `megalinter/megalinter:test-nvuillam-azure` ? :)

**Comment by lumarel** [comment]
@nvuillam Looks really good! :)
Just noticed that if somebody has self configured extraheaders, this won't work, but for me it is fine 😄

**Comment by nvuillam** [comment]
@lumarel I remove extraheaders only if I set them just before after detecting a variable GIT_AUTHORIZATION_BEARER ^^

**Comment by lumarel** [comment]
@nvuillam Yep I understood that, but I mean, if someone already set the extraheaders before the Container init, this will be overwritten, if the variable is provided :)
But that's an edge case, which might need a fix when somebody actually wants to do that ^^

**Comment by nvuillam** [comment]
Indeed a lot of ifs, we'll see when it happens 😅

**Comment by lumarel** [comment]
It is, I just noticed it, but don't need it anyway 🙂
