### ISSUE TITLE
Add 🐊`Putout` integration for JavaScript

### ISSUE THREAD

**Issue by coderaiser** [megalinter/megalinter#1127]
Hi, thank you for such a useful project!
**Is your feature request related to a problem? Please describe.**
Would be great to have 🐊[`Putout`](https://github.com/coderaiser/putout) linter integration with `megalinter` to lint (and maybe `fix`) `JavaScript`, `TypeScript`, `JSON`, `Markdown` and `Yaml` files. But first of all `JavaScript` :)! 
**Describe the solution you'd like**
What do you think about adding 🐊`Putout` to `megalinter`? What should be done from my side to get things working?

**Comment by nvuillam** [comment]
I like your style and the style of your documentation, I'll try it on npm-groovy-lint to see if it can really rewrite more nicely some code that is not so nice sometimes  ;)

As far as I understand, putout is a code rewriter, so as MegaLinter is a linter/fixer, I wouldn't like to scare its users if they see their code rewritten whereas they just wanted to lint/fix it, so we could enable putout only when there is a `.putout.json` config file at the root of the repository

Would you like to make a pull request ? :)
All MegaLinter needs is descriptive parameters in a descriptor file (you can see what is done for [Javascript](https://github.com/megalinter/megalinter/blob/main/megalinter/descriptors/javascript.megalinter-descriptor.yml) for example )

https://megalinter.github.io/latest/contributing/#add-a-new-linter

**Comment by coderaiser** [comment]
> I like your style and the style of your documentation, I'll try it someday on npm-groovy-lint to see if it can really rewrite more nicely some code that is not so nice sometimes ;)

Thank you :)

> As far as I understand, putout is a code rewriter, so as MegaLinter is a linter/fixer, I wouldn't like to scare its users if they see their code rewritten whereas they just wanted to lint/fix it, so we could enable putout only when there is a .putout.json config file at the root of the repository

Actually 🐊`Putout` reports only about found errors and apply fixes only when `--fix` parameter used.

> Would you like to make a pull request ? :)

Sure :)
