### ISSUE TITLE
tflint --init does not take variables

### ISSUE THREAD

**Issue by guruvamsichintala5** [megalinter/megalinter#1134]
**Describe the bug**
Pre command "tflint --init" does not take environment variables

From the PR https://github.com/megalinter/megalinter/pull/649 this only runs "tflint --init" command and does not take consider any TERRAFORM_TFLINT-* variables defined.

We configured our .tflint.hcl file in a directory called megalinter (not in the root directory). So we defined the variable TERRAFORM_TFLINT_RULES_PATH : megalinter

but "tflint --init" does not consider the variable and does not initialize the plugins defined. 

We have a workaround  to define a PRE_COMMAND with "tflint --init -c megalinter/.tflint.hcl"

Can you please fix this

**Comment by guruvamsichintala5** [comment]
Seeing the same behavior for **dockerfilelint** linter.

Created custom rules file **.dockerfilelintrc** in a subdirectory "**megalinter**" but the linter does not use the values.

Tested on my local with command **"dockerfilelint.cmd Dockerfile -c .\megalinter"** and it works as expected but not working with mega linter

**Comment by nvuillam** [comment]
I understand the issue, tflint --init must be called before actually running tflint, i'll make the update

Meanwhile you found the right workaround :)

**Comment by guruvamsichintala5** [comment]
> 

Solution would be "**tflint --init"** accepting any defined parameters in .megalinter before running **tflint**

Sounds good for using hadolint instead of having multiple linters for same type of files.

**Comment by nvuillam** [comment]
Having automated pre-commands with variables is today not possible with MegaLinter descriptor architecture.... but luckily, we can associate a custom class to a linter, and override default Linter.py methods, and for this case it would be `TfLintLinter.before_lint_files(self)`, like [here](https://github.com/megalinter/megalinter/blob/4b9490aa3bd654924f9be240465b31f1bfc1ec7b/megalinter/linters/RakuLinter.py#L16) (saying that just in case you'd like to help by making the PR ^^ )

**Comment by nvuillam** [comment]
@guruvamsichintala5 Please could you check that now it is ok with megalinter/megalinter:beta without PRE_COMMANDS workaround ? :)

**Comment by guruvamsichintala5** [comment]
Thanks a lot @nvuillam. beta version is working fine and as expected.

TERRAFORM_TFLINT is taking the variables defined in .gitlab.yml file and running the pre-commands without defining them

**Comment by nvuillam** [comment]
@guruvamsichintala5 that's great , thanks for your feedback :)
That's even available in latest v5 (v5.7.0) if you like :)

Warning: if you have sql files in your repo, you better wait 5.8.0 to upgrade, as there is an issue with sqlfluff

**Comment by guruvamsichintala5** [comment]
Sure Thanks for the information @nvuillam  :)
