### ISSUE TITLE
[Help Wanted] TERRAFORM_KICS taking a long time to run comparing to TERRAFORM_CHECKOV

### ISSUE THREAD

**Issue by dgteixeira** [megalinter/megalinter#1185]
# Description

Hello, I don't know if this is the correct place to do this, but I've recently enabled `TERRAFORM_KICKS` in my enabled_linters list within `.mega-linter.yml`, after been using `TERRAFORM_CHECKOV` and `TERRAFORM_TFLINT` for over 5 months.

After a few runs of this enabled linter, I saw that the elapsed time between linters is very disproportional between them, while using the default configuration ( to note: megalinter only checks the changed files, not the whole repo).

Kics takes many degrees longer than checkov or tflint. Is this just like this, a problem on kics side or anything else?

Can anyone help me out with this?

Below I share my megalinter configuration and a result table to prove my point.

## Code sampling

My `.mega-linter.yml` file:
```
# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
DEFAULT_BRANCH: main # Usually master or main
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - TERRAFORM_CHECKOV
  - TERRAFORM_TFLINT
  - TERRAFORM_KICS
  - MARKDOWN_MARKDOWNLINT
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - CREDENTIALS_SECRETLINT
  - KUBERNETES_KUBEVAL
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
IGNORE_GITIGNORED_FILES: true # If set to true, Mega-Linter will skip files ignored by git using .gitignore file
KUBERNETES_DIRECTORY: k8s
KUBERNETES_KUBEVAL_ARGUMENTS: "--schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/ --ignore-missing-schemas"
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT
```

## Megalinter result example

We can see in the image below, that for the same 4 files (the ones that were changed), the difference was **6x** (!!!)
![image](https://user-images.githubusercontent.com/48694843/150400690-cd8eb692-fdfe-4e41-86cb-c89743c837ff.png)

Thanks for the help!

**Comment by nvuillam** [comment]
For the moment, kiks and checkov are called one time for each .tf file, and your repo probably has lots of them
Maybe checkov has a cache management than kics does not have...
This will be enhanced in a next version, to browse the whole repository with just one call :)

**Comment by dgteixeira** [comment]
Ok, cool, thanks!
You need me to open a feature request for that improvement?

**Comment by nvuillam** [comment]
Nope it's ok let's let this one open :)
