### ISSUE TITLE
Ability to use my own docker image

### ISSUE THREAD

**Issue by fchastanet** [megalinter/megalinter#1186]
**Is your feature request related to a problem? **
I already have a docker image with all the needed linter and build tools, I want to reuse it to run mega-linter on it

**Describe the solution you'd like**
would it be possible to add a parameter instead of --flavor that would be --docker-image for example ?

**Describe alternatives you've considered**
Or would it be possible to run it directly inside my own docker image without having to download any flavor ?

**Additional context**
N/A

**Comment by nvuillam** [comment]
How did you build such docker image ?

**Comment by fchastanet** [comment]
I was thinking about extending my image installing some tools like you do in your flavors
And that I could reuse most of tools I was using in my build image but finally no, It's even the reverse I will remove some tools from my build image.
So we can close this issue.
And thanks for this projects.

**Comment by nvuillam** [comment]
Not sure I understood everything, but if you need more tools & linters within MegaLinter, there are several ways to do that:
- [MegaLinter plugins](https://megalinter.github.io/latest/plugins/)
- [MegaLinter PRE_COMMANDS and POST_COMMANDS](https://megalinter.github.io/latest/configuration/#pre-commands)
- and Request new linter integrations :)
