### ISSUE TITLE
[v5.6.0] Linter descriptor links error

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#1190]
**Describe the bug**
404 occured when you follows (click on) linter descriptors links

**To Reproduce**
Click on link in right side of linter . Try to follow https://megalinter.github.io/v5/descriptors/php_phplint

```
 ### Processed [PHP] files
- Using [phplint v3.0] https://megalinter.github.io/v5/descriptors/php_phplint
- MegaLinter key: [PHP_PHPLINT]
- Rules config: [/github/workspace/.github/linters/.phplint.yml]
✅ Linted [PHP] files with [phplint] successfully - (2.71s)
```

**Expected behavior**
Redirection to documentation page OK

**Screenshots**
404 occurs

**Comment by nvuillam** [comment]
oh , seems like a regression :(
I check that right away, thanks for the catch !

**Comment by llaville** [comment]
Thanks ❤️
