### ISSUE TITLE
Allow SQLFluff configuration to be read from usual location

### ISSUE THREAD

**Issue by tunetheweb** [megalinter/megalinter#1199]
**Is your feature request related to a problem? Please describe.**
SQLFluff 0.9.0 added the ability to specific a config file location in the command line, rather than picking it up from the directory tree being linted.

**Describe the solution you'd like**
Add `.sqlfluff` file to TEMPLATES directory and necessary code changes to pick it up (`sqlfluff lint --config CONFIG_FILE)`

The only caveat is that any command-line supplied config will override any other config, so it should be commented out by default so anyone using a local one in their code base can continue to use this.

**Describe alternatives you've considered**
Could leave it as is, but would be nice for consistency to be able to do this.

**Additional context**
I recently opened a PR to add this to the GitHub super linter: https://github.com/github/super-linter/pull/2361
I presume similar changes are needed here as this started life as a fork of that.

**Comment by nvuillam** [comment]
@tunetheweb your PR seems ok, let's see what CI says :)

Just to be sure, now the current behaviour of MegaLinter with sqlfluff is the following:
- if .sqlfluff config is found at the root , it will be used: `--config .sqlfluff`
- else, default .sqlfluff that you defined in /templates will be used: `--config pathToDefault/.sqlfluff`

If you want the default behaviour is to let .sqlfluff find itself a .sqlfluff config file, you need to remove the default config file in /templates

**Comment by tunetheweb** [comment]
> If you want the default behaviour is to let .sqlfluff find itself a .sqlfluff config file, and use its internal default rules if not found, you need to remove the default config file in /templates

SQLFluff will always find any config files (even if you specify one on the command line), so we don't need MegaLinter to do that for us.

This logic allows some config to be global for that project (for `/.sqlfluff` file), and then that global config to be overwritten for SQL in a folder that needs special config (e.g. `/sql/.sqlfluff` file for `/sql/tests.sql`), and both of those to be override if giving in a command line (e.g. sqlfluff lint --config /templates/.sqlfluff).

However by commenting out `/templates/.sqlfluff` lines it's basically has no effect by default, unless someone uncomments it. This allows us to introduce this config file as a non-breaking change (the local config files will still be used) and should only be used if people who just want one config file, without any local overriding for any folders.

Get me?

**Comment by nvuillam** [comment]
That's clear :)

**Comment by tunetheweb** [comment]
Glad you think so! Nearly confused myself just writing it! 😁
