### ISSUE TITLE
Allow Eslint with config in package.json

### ISSUE THREAD

**Issue by vitaliytv** [megalinter/megalinter#1205]
Eslint can use config declared in package.json "eslintConfig"

https://eslint.org/docs/user-guide/configuring/

**Comment by nvuillam** [comment]
That's good, but we need to check if eslintConfig is present in json :)
Maybe some format like **filename[text]** package.json[eslintConfig] , and in the python code, detect when `[` is present in a file name, and in that case : 
- check for the file existence
- open the file and check if the text is present inside
