### ISSUE TITLE
secretlint is not respecting ignored files

### ISSUE THREAD

**Issue by schorlton** [megalinter/megalinter#1207]
**Describe the bug**
As per title, secretlint is erroring on files that are in my `.gitignore` and recognized by megalinter to be ignored. Important lines from the log:

```
- Excluding .gitignored files [219]: /tmp/lint/.env
[Filters] {'name': 'CREDENTIALS_SECRETLINT', 'filter_regex_include': None, 'filter_regex_exclude': None, 'files_sub_directory': None, 'lint_all_files': True, 'lint_all_other_linters_files': False, 'file_extensions': [], 'file_names_regex': [], 'file_names_not_ends_with': [], 'file_contains_regex': []}
CREDENTIALS_SECRETLINT linter kept 0 files after applying linter filters:
[secretlint] command: ['secretlint', '--secretlintrc', '/action/lib/.automation/.secretlintrc.json', '**/*']
[secretlint] result: 1
[4m/tmp/lint/.env[24m
  [90m1:18[39m  [31merror[39m  [AWSAccessKeyID] found AWS Access Key ID: xxxxxxxxxxxxxx
```

Thanks for your help and amazing tool!

**Additional context**
Running docker image `megalinter/megalinter:5.6.0`

**Comment by nvuillam** [comment]
@schorlton thanks for noticing, PR to arrange that is on the way :)

**Comment by nvuillam** [comment]
@schorlton you can check with megalinter/megalinter@beta ( or its flavors beta version ), once [this job](https://github.com/megalinter/megalinter/runs/4966518077?check_suite_focus=true) is completed :)

**Comment by schorlton** [comment]
Awesome, it's fixed! Thanks so much @nvuillam

**Comment by nvuillam** [comment]
You're welcome :)

**Comment by schorlton** [comment]
@nvuillam : secretlint is super slow...what are your thoughts on getting secretlint to respect the megalinter ignored files instead of just the `.gitignore`?  I'm not sure it's the best for the user to lint the entire directory if say it's a massive directory and some of the stuff is submodules and therefore not git ignored. Also, this would be the consistent behaviour with the rest of megalinter. Thanks for your consideration!
