### ISSUE TITLE
What is npx?

### ISSUE THREAD

**Issue by nigelhorne** [megalinter/megalinter#1212]
The documentation says to run the npx command, but doesn't say where you get npx from.  "yum install npx" fails, and "npx" gives "command not found".

**Comment by llaville** [comment]
This will probably help you to understand what is npx : https://www.freecodecamp.org/news/npm-vs-npx-whats-the-difference/

**Comment by nvuillam** [comment]
@nigelhorne indeed we should update the doc tobadd to install node.js before running npx :)

**Comment by nigelhorne** [comment]
Thanks, but that didn't help.

I ran "yum install nodejs" and I still get "npx: command not found"

**Comment by nvuillam** [comment]
That's strange... but I don't have centOs experience, maybe add sudo to install nodejs ? -> https://linuxize.com/post/how-to-install-node-js-on-centos-7/

Can you also check the following commands ?
- `node --version`
- `npm --version`

**Comment by nigelhorne** [comment]
```
$ node --version
v6.17.1
$ npm --version
3.10.10
```

**Comment by nvuillam** [comment]
That's a very old node.js version, apparently with yum the package name contains the version (cf https://nodejs.org/en/download/package-manager/#centos-fedora-and-red-hat-enterprise-linux )

![image](https://user-images.githubusercontent.com/17500430/152565528-f460b175-f257-48c0-a7ee-a5c77a9d3d19.png)
