### ISSUE TITLE
Upgrading CSpell examples

### ISSUE THREAD

**Issue by Jason3S** [megalinter/megalinter#1220]
I maintain [cspell: A Spell Checker for Code!](https://github.com/streetsidesoftware/cspell)

It looks like some of the auto-generated `cspell.json` files are out of date. 

https://github.com/megalinter/megalinter/blob/4aa6dd8956db9a9835af6b5fc1850f91b6c498b7/megalinter/linters/CSpellLinter.py#L32

Version should be `"0.2"`. I also suggest setting up a custom dictionary by default.

**Comment by nvuillam** [comment]
@Jason3S thanks for the tip !
I'll do the "convert to dictionary" part later, as it requires more advanced development, and maybe add MegaLinter users an option to choose the additional words config method :)
