### ISSUE TITLE
Change Log Linter Version

### ISSUE THREAD

**Issue by schorlton** [megalinter/megalinter#1223]
Not sure how the change log gets generated, but noticed this:
`  - [shfmt](https://github.com/mvdan/sh) from 3.2.1 to **3.5.0** on 2022-01-30`
https://github.com/megalinter/megalinter/blob/4069f0dafe5c38c3125609a624f010c168b0c5d3/CHANGELOG.md?plain=1#L65

Interestingly, when I go to https://github.com/mvdan/sh, I see the latest version at `3.4.2`...any idea how the change log here is ahead of latest `shfmt`?

![image](https://user-images.githubusercontent.com/10245822/151710701-c6279f30-15e1-443f-8284-016215260e1a.png)

Thanks as always!!!

**Comment by nvuillam** [comment]
I changed the way of installing shfmt in MegaLinter docker images, now it uses docker image mvdan/shfmt:latest-alpine

2 days ago they released a new one, so maybe it's a pre-release or something like that ^^

https://hub.docker.com/r/mvdan/shfmt/tags

If you want to know why, maybe you can ask on [shfmt repo](https://github.com/mvdan/sh) :)

**Comment by schorlton** [comment]
Thanks! :smile:

**Comment by echoix** [comment]
There is a v3.5.0-0.dev tag in the git repo, but it dates to Oct 2, 2021, while v3.4.0 tag was released Oct 1, 2021. The current release and tag is v3.4.2 on Dec 24, 2021.

So, if you run this you get the 3.5.0
```console
$ docker run -it mvdan/shfmt:latest --version
v3.5.0-0.dev-49-g976895f5
```

I see that there was a commit here that tried to install shfmt using apk, but was overwritten by another pull request inside 24h.

**Comment by nvuillam** [comment]
@echoix apk install installed a previous version :/

The safer way will probably to force 3.4.2 by using the related docker image...

Or to make latest-alpine really be the latest alpine image , I'll ask shfmt maintainers :)

**Comment by echoix** [comment]
> apk install installed a previous version :/

However, the packaging process of Alpine in the `community` repo, `edge` branch is quite up to date, they picked up the new release and pushed the new release inside of 7 h.

This installs from the edge/community one time, without adding it the repo list. There are no dependencies either, and since its statically linked, there shouldn't be any side effects.
```shell
apk add --update --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community shfmt 
```
