### ISSUE TITLE
Unable to change the report directory

### ISSUE THREAD

**Issue by GrabCAD-Gary** [megalinter/megalinter#1256]
**Describe the bug**
I am unable to change the `report` directory. I tried setting `REPORT_OUTPUT_FOLDER` but nothing I give it works, with or without quotes, with or without `GITHUB_WORKSPACE` in the path. I tried setting `GITHUB_WORKSPACE` to something local but anything I give that causes ML to crash with a `NoSuchPathError`, which is probably because the context is the Docker container.

Whilst this is happening all report output to files fails. No output appears in `reports` or anywhere else I can find. I've used tools to do system-wide searches. It just disappears and no errors are reported. That's not good.

**To Reproduce**
Set `NoSuchPathError` to anything other than the default.

**Expected behavior**
We should be able to change the output dir to something more descriptive and less likely to cause clashes.

Thanks.

**Comment by nvuillam** [comment]
That's really strange, it's supposed to work ...

How do you run MegaLinter ? GH Action ? Docker image ? mega-linter-runner ?

Note: in v6, default report folder will be renamed into `megalinter-reports`
