### ISSUE TITLE
Support kubeconform

### ISSUE THREAD

**Issue by onedr0p** [megalinter/megalinter#1268]
**Is your feature request related to a problem? Please describe.**

:wave: kubeval is mostly outdated and rarely updated, it would be neat to support kubeconform

https://github.com/yannh/kubeconform

**Comment by nvuillam** [comment]
Great idea :)
I can do that someday, or another contributor with some available time :)

**Comment by Yann-J** [comment]
FYI, just gave it a try...

**Comment by nvuillam** [comment]
@Yann-J congrats, you seem very close to success :)
