### ISSUE TITLE
Dockerfile linter support detect both "Dockerfile" and"dockerfile"

### ISSUE THREAD

**Issue by ThomasRunting** [megalinter/megalinter#1275]
can the docker file  regex detect both upper and lower case versions

**Describe the solution you'd like**
mod regex to detect lowercase version as well

**Comment by nvuillam** [comment]
I prefer to keep regex matching case sensitive,but you can solve the issue by defining the following variable in your .mega-linter.yml file :)

```yaml
DOCKERFILE_HADOLINT_FILE_NAMES_REGEX:
  - Dockerfile
  - dockerfile
```

**Comment by ThomasRunting** [comment]
it works. but ive found things with it refenced in both ways and more likely in the lowercase format

**Comment by nvuillam** [comment]
Glad it works, thanks for your feedback !

The standard file name is Dockerfile with a big D, so I prefer to keep lowercase management as a workaround :)
