### ISSUE TITLE
secretlint should respect megalinter ignored files/folders instead of .gitignore

### ISSUE THREAD

**Issue by schorlton** [megalinter/megalinter#1277]
Opening this up as a separate issue from https://github.com/megalinter/megalinter/issues/1207#issuecomment-1028585281 to keep it on your radar as it really does slow down the megalinter experience dramatically. Thanks again!!!

**Comment by nvuillam** [comment]
@schorlton now that .gitignore is automatically sent to secretlint when there is a gitignore + no secretlintignore, what do you think is remaining to do ? ^^

**Comment by schorlton** [comment]
Hi @nvuillam , thanks for circling back. Ideally `secretlint` would respect the ignored files in `.mega-linter.yml` instead of requiring its own secretlintignore? If `secretlint` needs a file listing files to ignore, perhaps something like writing megalinter's ignored files to a temp file and passing that to `secretlint`?

**Comment by nvuillam** [comment]
It would work if we had a .megalinterignore with same format than .gitignore ... maybe someday :) ( I agree that FILTER_REGEX_EXCLUDE is not so nice to use... )

**Comment by schorlton** [comment]
No worries! I seems like megalinter has a list of files internally that it is ignoring after it parses `FILTER_REGEX_EXCLUDE`...why not write that list to a tempfile and specify that tempfile to secretlint (or put it in in secretlintignore) if possible?

**Comment by nvuillam** [comment]
MegaLinter keeps the "not filtered" list of files, but not the filtered ones... maybe it could indeed be possible, but to be honest, it will probably wait for v6 except if a good soul decides to make a PR before ^^
