### ISSUE TITLE
GithubStatusReporter is not working for PR

### ISSUE THREAD

**Issue by ankitbko** [megalinter/megalinter#1279]
https://github.com/megalinter/megalinter/blob/b9f17545cf5391b20c97a9410f72081da3077d17/megalinter/reporters/GithubStatusReporter.py#L40

I see commit is read from "GITHUB_SHA" which is merge commit in case of PR and the git is in detached state. For PR we need to find the HEAD commit for the PR and use that commit.

**Comment by ankitbko** [comment]
The repo is private with self hosted agent but I can share some screenshots.

Here is the commit for which the action ran on PR
![image](https://user-images.githubusercontent.com/3169316/154790569-9a29d042-e1e1-4969-a12d-5d149a531117.png)


Below is the git checkout step. You can see it merging 744a7b2a with main branch and creating a merge commit 3a2bf9a.
![image](https://user-images.githubusercontent.com/3169316/154790386-d8484b7b-79c3-4b2c-98c3-cd3de03d66b2.png)

The merge commit 3a2bf9a is what is assigned as GITHUB_SHA
![image](https://user-images.githubusercontent.com/3169316/154790425-33b2f9b5-7342-411b-a32e-772d0b9b9ed3.png)

And the status is being set on merge commit 3a2bf9a
![image](https://user-images.githubusercontent.com/3169316/154790464-0135856c-9b61-4690-a0ba-efdcb0560103.png)

**Comment by ankitbko** [comment]
The above is expected behavior by github action - https://github.community/t/github-sha-not-the-same-as-the-triggering-commit/18286

I went through source code of couple of other actions I am using and they are getting HEAD commit of PR instead of relying on GITHUB_SHA if the action trigger was PR.

https://github.com/EnricoMi/publish-unit-test-result-action/blob/master/python/publish_unit_test_results.py#L135
https://github.com/5monkeys/cobertura-action/blob/717143c6305698f49686e4def6c1156671b3499a/src/action.js#L304

I think something different but on the similar line was done for GithubCommentReporter, i.e not relying on GITHUB_SHA for PR triggered action https://github.com/megalinter/megalinter/pull/526/commits/d1fc69f64481e27e0e142d66c8d8f8147b91b7d2#diff-81c879afcb1f3042d4dc87997faa89145d5891aa9a9ceeee89a5313268b4c0a1R194

**Comment by nvuillam** [comment]
Thanks for the great analysis !

I'm short on time these days... would you like to make a PR ?

**Comment by ankitbko** [comment]
@nvuillam  So I have done a quick fix for this but I dont know how to run Megalinter from forked repo to test this code. Can you help me with testing this?

**Comment by nvuillam** [comment]
I retrieved your updates in a local branch and made a test PR -> https://github.com/megalinter/megalinter/runs/5279839076?check_suite_focus=true
It will generate a docker image that we'll be able to use for tests :)

**Comment by ankitbko** [comment]
Thanks a lot. There are 2 minor linting error. Would appreciate if you could fix it in your branch and rebuild the PR

**Comment by Kurt-von-Laven** [comment]
Thanks for sharing what worked for you! Did you mean `VALIDATE_ALL_CODEBASE=true` instead of `VALIDATE_ALL_CODEBASE=false=true`?

**Comment by Yann-J** [comment]
> Thanks for sharing what worked for you! Did you mean `VALIDATE_ALL_CODEBASE=true` instead of `VALIDATE_ALL_CODEBASE=false=true`?

Haha yeah, good catch, indeed!

For anyone in a similar situation (code in Github but build in Azure devops), I'm also sharing here the exact working Megalinter invocation, to show how Azure variables map to what ML reporters expects:

```
      if [[ "${BUILD_REASON}" == "PullRequest" ]]; then
        echo "This is a PR build, scanning delta only"
        export VALIDATE_ALL_CODEBASE=false
        export GITHUB_SHA=$(git log -1 --pretty=%B | sed -e 's/^Merge //' -e 's/ into.*//')
      else
        echo "This is a regular build"
        export VALIDATE_ALL_CODEBASE=true
        export GITHUB_SHA=${BUILD_SOURCEVERSION}
      fi

      docker run -v "$(System.DefaultWorkingDirectory):/tmp/lint" \
        -e GITHUB_TOKEN \
        -e VALIDATE_ALL_CODEBASE \
        -e APPLY_FIXES=none \
        -e GITHUB_STATUS_REPORTER=true \
        -e GITHUB_COMMENT_REPORTER=true \
        -e CI=true \
        -e GITHUB_REF=$(Build.SourceBranch) \
        -e GITHUB_REPOSITORY=$(Build.Repository.ID) \
        -e GITHUB_TARGET_URL="$(System.CollectionUri)/$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=logs&j=$(System.JobId)&t=$(System.TaskInstanceId)" \
        -e GITHUB_SHA \
        -e LOG_LEVEL=debug \
        oxsecurity/megalinter-cupcake:v6
```
