### ISSUE TITLE
What does "Reference status" mean in the list of linters

### ISSUE THREAD

**Issue by echoix** [megalinter/megalinter#1286]
Hello!

I have a little question about the docs, in the list of linters page, https://megalinter.github.io/latest/all_linters/
![image](https://user-images.githubusercontent.com/27212526/154847730-50593ae6-b82b-47b8-8b9e-6b512f6a3163.png)
What does the "Reference status" column and the icons mean? There are white circles, hearts, no entry signs, and hammer & wrench icons.

Thanks!

**Comment by nvuillam** [comment]
I try to add a link to MegaLinter in the linters own documentation :)

If the PR has been accepted, a heart icon is displayed
If the PR is pending, love letter icon is displayed
If the PR has been rejected , a blocking sign is displayed
If not PR has been done, grey icon is displayed :)

The related code is the following in build.py, using `linter_megalinter_ref_url` property

![image](https://user-images.githubusercontent.com/17500430/154858557-83f60cc5-52bd-4340-a1f9-b58f1049630e.png)

**Comment by nvuillam** [comment]
Please feel free to make PR in the linters that do not refer to MegaLinter yet, they are generally more welcomed when they are not coming from the repo owner^^

**Comment by echoix** [comment]
Thanks for the clarification here, I didn't understand on the published web page.

**Comment by nvuillam** [comment]
You're welcome :) it is not clear on the doc, agreed ^^
