### ISSUE TITLE
Add shell script linters to ci_light flavor

### ISSUE THREAD

**Issue by wesley-dean** [megalinter/megalinter#1298]
**Is your feature request related to a problem? Please describe.**
I have a small project that is, essentially, a shell script that's to a base image via a Dockerfile.  I would like to be able to have the scanner just hit the relevant parts (and just pull down the relevant scanner layers).

**Describe the solution you'd like**

Add the `BASH_*` linters to the `ci_light` flavor.

**Describe alternatives you've considered**

Use the full scanner with all of the linters, most of which aren't run due to a lack of content matching them.

**Additional context**

Example: [wesley-dean/rsyslog-newrelic-forwarder](https://github.com/wesley-dean/rsyslog-newrelic-forwarder)

**Comment by nvuillam** [comment]
Good idea :)

I's on the way ^^
