### ISSUE TITLE
Text and console reporters links to non-existing documentation pages for plugins

### ISSUE THREAD

**Issue by mjpieters** [megalinter/megalinter#1340]
**Describe the bug**

When using a plugin (such as [jupyfmt](https://github.com/kpj/jupyfmt#mega-linter-integration), several reporters output links to a non-existing page.

E.g. the text reporter:

```
Results of jupyfmt linter (version 0.5.1)
See documentation on https://megalinter.github.io/descriptors/jupyter_jupyfmt/
```

and the console reporter:

```
- Using [jupyfmt v0.31.0] https://megalinter.github.io/v5/descriptors/jupyter_jupyfmt
```

**To Reproduce**

1. Create a minimal setup:

    ```sh
    cd $(mktemp -d -t mcve-XXXXXXXXXX)
    cat > .mega-linter.yaml <<EOF
    PLUGINS:
      - https://raw.githubusercontent.com/kpj/jupyfmt/master/mega-linter-plugin-jupyfmt/jupyfmt.megalinter-descriptor.yml
    ENABLE:
      - JUPYTER
    EOF
    touch dummy.ipynb  # so the linter has something to run against
    ```
2. Run `npx mega-linter-runner`

The console output will include:

```
### Processed [JUPYTER] files
- Using [jupyfmt v0.5.1] https://megalinter.github.io/v5/descriptors/jupyter_jupyfmt
```

and in `report/linters_logs/WARNING-JUPYTER_JUPYFMT.log`:

```
Results of jupyfmt linter (version 0.5.1)
See documentation on https://megalinter.github.io/descriptors/jupyter_jupyfmt/
```

**Expected behavior**

Either no documentation URL should be shown, or it should be possible for the plugin to define a URL, with a possible fallback to the `linter_url` value.

**Comment by nvuillam** [comment]
That's right, MegaLinter plugibs should redirect to the plugin documentation, i'll try to arrange that :)

**Comment by nvuillam** [comment]
That's right, MegaLinter plugins should redirect to the plugin documentation, i'll try to arrange that :)

**Comment by nvuillam** [comment]
@mjpieters it should be ok now (with beta version) :)
