### ISSUE TITLE
Github Comment Reporter: add configuration option for 'current run' link

### ISSUE THREAD

**Issue by mjpieters** [megalinter/megalinter#1341]
**Is your feature request related to a problem? Please describe.**

I'm running Mega-Linter in Jenkins, and provide `GITHUB_TOKEN`, `GITHUB_REPOSITORY` and `GITHUB_SHA` environment variables so the Github Reporter knows where to post a comment. This works great.

However, the comment ends with:

```
See errors details in MegaLinter reports
```

with no further context. However, I'm also uploading the Mega-Linter reports folder as artifacts, that I'd love to link here.

**Describe the solution you'd like**

The reporter could take a configuration parameter (`CI_ACTION_RUN_URL` perhaps?) that, if set, is used as the `action_run_url` variable in the reporter. If set, the reporter would ignore `GITHUB_RUN_ID` and not generate a URL based on that, but just use the provided URL.

I can then provide the URL as built from variables set by Jenkins, such as `${BUILD_URL}/artifacts`.

**Describe alternatives you've considered**

I would have to create a separate step that also posts a comment, as there is no option to alter the comment content before it is posted.

**Comment by nvuillam** [comment]
@mjpieters good proposition, PR is on its way :)
