### ISSUE TITLE
Github Pull Request inline reporting of errors from linters reports

### ISSUE THREAD

**Issue by nishwalshetty** [megalinter/megalinter#1350]
**Is your feature request related to a problem? Please describe.**
currently linter results are posted as comment, this invloves downloading the zip file and looking for errors, when we use all linters this becomes time consuimg, also most of the linters are run on complete file and not on changed code

**Describe the solution you'd like**
linter results to be posted as inline comment in the pull request (example below)
![image](https://user-images.githubusercontent.com/48088420/159852868-cdcdc23b-c6b3-45d3-be0a-c6e4dcbdad7f.png)

**Comment by nvuillam** [comment]
I think you will love MegaLinter v6, that will be released in some weeks:)

It will have a SARIF output reporter, and such SARIF file will be uploaded to Github that will display the errors directly within the code of the PR, like in your screenshot :)

In a first time, it will work only with linters that can themselves output a sarif report (see the supported linters on this page ->  https://megalinter.github.io/v6-alpha/supported-linters/ )

For the linters not managing sarif yet, I started to ask their maintainers, you can help by asking that too on such linters repos !

Star or watch the repo to be notified of the release ^^

**Comment by nishwalshetty** [comment]
awesome, looking forward for the release!

**Comment by davidB** [comment]
Looks great, I took a quick look to v6 PR SARIF definition seems to be define via descriptor by adding parameters, will v6 support translation via external tool?

Eg. for `clippy` that does not support SARIF natively  we can use an additional app `clippy-sary` and pipe output like `cargo clippy --message-format=json | clippy-sarif`

**Comment by nvuillam** [comment]
@davidB for the moment the focus has been set on linters managing SARIF (and I posted issues to ask for it on repos that do not manage it yet)

I think that for linters that won't manage sarif for a while, we probably can manage it using external tools like clippy-sarif, that could be done with descriptor additional properties, or using overriden Linter classes like ClippyLinter that you just created :)

**Comment by davidB** [comment]
Ok, I guess you prefer to wait for after the release of v6 to receive PR to add SARIF (vs PR on the v6_dev branch).

**Comment by nvuillam** [comment]
@davidB currently I woudn't advise to use v6_alpha as it is not finalized yet (target: beginning of may, with nice surprises 🤩 ), but I'd accept anytime a PR in v6_dev managing SARIF for clippy :)
