### ISSUE TITLE
Promote the megalinter template (for ffizer)

### ISSUE THREAD

**Issue by davidB** [megalinter/megalinter#1386]
Hi,

## Context

I created a template to install megalinter into project with [ffizer](http://github.com/ffizer/ffizer)  at https://github.com/ffizer/templates_default/tree/master/megalinter

- the template is based on the one used by npx megalinter ... (I remove useless variables)
- the template will be include a shell script to launch megalinter locally via docker/nerdctl

## Question

1. Can I make a PR into the doc to promote ffizer and this template (as an alternative to npx) ?
2. Can I wrote an article/tutorial for ffizer where I show how to create a composed template with the megalinter template where template creator can define other default, hide some questions,... ?

## Disclaimer

I'm the author of [ffizer](http://github.com/ffizer/ffizer) a project generator/updater, similar to yeoman, cookie cutter but with few differences:
- no dependencies (to a runtime, dev stack,...), it's a standalone binary (so need to install nodejs, npx,...)
- can be applied on existing project and propose to see diff, overwrite, skip,...
- templates can be tested
- templates can be composed with external template (eg: rust base + megalinter + ...)

**Comment by nvuillam** [comment]
@davidB 

- **The bad news**: I'd like to keep the control on the MegaLinter installer, so `npx mega-linter-runner --install` will remain based on yeoman for the moment :)

- **The good news**: Who the f*** would I be to tell anyone not to create anything that generates configuration files ? You are very welcome to create a MegaLinter template and associated article, and who knows, if someday it becomes so much better than MegaLinter internal one, we may integrate it in the repo :) Meanwhile, as I want users to use the main installer, I can put hyperlinks within Special Thanks and Articles section, but not on Installation page (i'm sure you understand ^^ )

**Comment by davidB** [comment]
I fully understand. A hyperlinks into the Articles section is fine.

Thanks for MegaLinter and the quick feedback.

**Comment by nvuillam** [comment]
You're welcome, plz ring me when the article is ready :)
