### ISSUE TITLE
How to force MegaLinter into failing when there is more than 0 in updated sources output?

### ISSUE THREAD

**Issue by bengeset96** [megalinter/megalinter#1389]
Hello project contributors and maintainers!

Is there possibility to make ML fail when there is fixed source file/s in /tmp/lint/report/updated_sources by default?

For now I am using `APPLY_FIXES: all`

This works awzm, but I really do not want to have anything in main branch without the updated sources fixed.

In ADO the current pipeline is successful even when there are fixes that should be applied. 

Currently just downloading the artifact and fixing, then new run. But I actually want the ML to fail when there is updated sources to be found so it will not merge into main (using ML as one of the validation steps in PRs). 

![image](https://user-images.githubusercontent.com/99641908/162226463-9a15b6cd-ea50-4b9b-8f4c-4e5386bd06e8.png)

![image](https://user-images.githubusercontent.com/99641908/162232533-ec900f24-7d42-4780-9f1a-37b65b217ba6.png)

Is it because I have disable errors for some of the linters and that will even change the once I have not disabled? 

Considering to do like this is needed, but unsure if this is the right tactic. 

`APPLY_FIXES: PRETTIER, ESLINT-PLUGIN-JSONC, MARKDOWNLINT
`

/Benjamin

**Comment by nvuillam** [comment]
Formatters are declared as "non blocking" by default, but you can set them blocking by default using FORMATTERS_DISABLE_ERRORS:false in .mega-linter.yml :)

**Comment by bengeset96** [comment]
@nvuillam 

Thanks!

When doing that, sure it fails. But even when output is 0.

`FORMATTERS_DISABLE_ERRORS:false` 

![image](https://user-images.githubusercontent.com/99641908/162276777-7b414731-b8c1-4eed-b024-23217cbe1556.png)

When `FORMATTERS_DISABLE_ERRORS:true`

![image](https://user-images.githubusercontent.com/99641908/162276946-c6e483c7-f692-4913-922b-53aadbc13675.png)

It seems like this formatters disable errors is also applicable for other things just than autofix, also normal errors. Here we can see that is seems like does not work for markdownlint. 

Also confirmed with seeing that ML start with saying markdownlint is configured with autofix, since .mega-linter.yml has `APPLY_FIXES:all `

![image](https://user-images.githubusercontent.com/99641908/162277549-3d05497d-0357-4c1e-b643-547178c1ab27.png)

Then I think it is actually quite nice to use `FORMATTERS_DISABLE_ERRORS:false` if autofix is not working for everything inside some linters like 57 errors here autofix is not able to solve.

**Comment by bengeset96** [comment]
Solution provided by @nvuillam 
`
FORMATTERS_DISABLE_ERRORS: false`

Configure behavior of linters might be needed, as autofix can't solve everything, because some of the issues will be ''impossible'' for linter to change, like length. 

In my case i just added .markdownlint.json with

```
 "MD013": {
    "line_length": 1000
```

**Comment by bengeset96** [comment]
@nvuillam 

Today I got some code with not optimal hygiene in main branch and it was not discovered before some hours later.

You have any idea how this is possible when using 

`FORMATTERS_DISABLE_ERRORS: false`

![image](https://user-images.githubusercontent.com/99641908/163257304-718ae9d2-5cf8-4370-b413-92891b78e2e1.png)

![image](https://user-images.githubusercontent.com/99641908/163257518-f947018e-4e90-4fd3-9a7d-90ab4125704c.png)

When I look more into the MegaLinter run.

![image](https://user-images.githubusercontent.com/99641908/163257690-0e12c816-c41d-40b4-803c-d8ad2f8c4056.png)

![image](https://user-images.githubusercontent.com/99641908/163257785-42ea24d8-9f20-4eb4-ada3-e9e65ccc65e0.png)

How can I force this to fail?

**Comment by nvuillam** [comment]
You can define `APPLY_FIXES: none` so no fix will be performed , and formatters will just check if format is ok, and if not they will fail

**Comment by bengeset96** [comment]
@nvuillam 

Will I still get the output with updated sources so copy paste can be used into repo or will I loose that functionality as a trade-off?

**Comment by nvuillam** [comment]
If you don't want to apply fixes, it will indeed not apply fixes, so no more updated_sources :/
Maybe you would like so additional option to do "apply_fixes but fail if fixes has been found" ?

**Comment by bengeset96** [comment]
@nvuillam 

Yes. When working with trunk based development strategy MegaLinter is a game changer. For us it has been completely night and day difference, but I need the tooling to give me this expected behavior when it is a major player in branch policy PRs into main branch. 

So apply fixes, but have the pipeline fail. Then you must manually download the artifact and copy the updated sources. Dev do new commit to PR. Pipeline is launched again. This time 0 in updated sources so green and passes checks and merge into main. 

Do you think that is something you could be able to do? 💯

**Comment by nvuillam** [comment]
@bengeset96 it has been asked so nicely, and it's a tiny update to do... so what monster would I be to refuse ? ^^

PR on the way :)

**Comment by bengeset96** [comment]
@nvuillam 

So kind of you! Using MegaLinter on all repositories, so this will help tremendously. 

It will also have cleaner merge history into main branch for better hygiene as you do not have to create own PR with autofixes. 💯 

Thank you for the effort 🥇

**Comment by nvuillam** [comment]
You're welcome :) 
PR CI jobs are long and I have to go to sleep so PR should be merged tomorrow and the evolution will be available in `megalinter/megalinter:beta` version , and in official release later

If you like MegaLinter, don't hesitate to support us by starring the repo and spread the word around you :)

**Comment by bengeset96** [comment]
Great!

I will test it out when it is available for the beta image and give feedback 😊

**Comment by bengeset96** [comment]
@nvuillam 

Did the CI/CT/CD fail? I can see the PR from your side, but validation failed? 

Unlucky 😃

**Comment by nvuillam** [comment]
There is a general error, probably related to gitpython library... the git diff called internally within MegaLinter crashes everytime... I'll have to solve that issue before being able to make any CI job pass :/

**Comment by bengeset96** [comment]
Typical.

Crossing my fingers for library, not fun times 😔

**Comment by nvuillam** [comment]
@bengeset96 I'm really sorry, but all MegaLinter is stuck for updates... I think it's related to new git version (and I can not downgrade because it contains CVE fixes) ...

I asked for help to gutpython masters, let's cross fingers that I'll have it :)

https://github.com/gitpython-developers/GitPython/issues/1431

**Comment by bengeset96** [comment]
Hoping for that gitpython kungfu's can assist with this matter :)

**Comment by nvuillam** [comment]
@bengeset96 I (think I) solved it :)

When this action is complete, you can check with beta version :)

**Comment by nvuillam** [comment]
Just add `FAIL_IF_UPDATED_SOURCES: true` in your .mega-linter.yml :)

**Comment by nvuillam** [comment]
mmm I fixed internal CI... but some errors are remaining... https://github.com/megalinter/megalinter/issues/1416

Sorry for convenience

**Comment by Kurt-von-Laven** [comment]
An additional (not mutually exclusive) option if you desire to run MegaLinter locally as well would be to run it as [a pre-commit hook](https://github.com/ScribeMD/pre-commit-hooks#megalinter). [pre-commit](https://pre-commit.com/) automatically fails whenever any hook updates any sources. @nvuillam, I will contribute more general versions of the hook to the official MegaLinter repo soon. Wanted to test them on myself before opening my big mouth and claiming victory.

**Comment by nvuillam** [comment]
@Kurt-von-Laven you're very welcome to add pre-commit hook directly within MegaLinter repo 😀

**Comment by bengeset96** [comment]
@nvuillam 

Have done some testing, but for some reason V8R linter does not like the added schema in .mega-linter.yml (FAIL_IF_UPDATED_SOURCES: true)

![image](https://user-images.githubusercontent.com/99641908/163843331-7df89ab2-e707-44ea-8226-b7a25e0075a0.png)

Do you have any idea? 

I want to :shipit:

**Comment by bengeset96** [comment]
Thanks!

No worry, this safe.directory is making many crash cases for other repos currently 👎 

From what I can see beta is sometimes crashing on some of the pipeline runs, v5 seems to be stable.
