### ISSUE TITLE
`target=blank` shown in documentation

### ISSUE THREAD

**Issue by tunetheweb** [megalinter/megalinter#1408]
**Describe the bug**

<img width="746" alt="image" src="https://user-images.githubusercontent.com/10931297/162906473-d9d529e7-3e81-4f2c-ac83-6c433a57225b.png">

**To Reproduce**

1. Go to https://github.com/megalinter/megalinter/blob/main/docs/descriptors/sql_sqlfluff.md#readme
2. Note the `target=blank`s

**Expected behavior**

These are part of the links to open in new windows and should not be displayed

**Screenshots**
As per above.

**Additional context**
N/A

**Comment by nvuillam** [comment]
That's because documentation is supposed to be browsed online :)

https://megalinter.github.io/latest/descriptors/sql_sqlfluff/

Documentation is generated by mkdocs-material, and make such hyperlinks open in new browser :)

**Comment by tunetheweb** [comment]
P.S. Nice docs in that site!

**Comment by nvuillam** [comment]
Thanks :)
I just auto-generate markdown from descriptors ... all the merit of the "nice" go to mkdocs-material, very easy to use if you are interested :) (it's just a [mkdocs.yml file](https://github.com/megalinter/megalinter/blob/main/mkdocs.yml) )

https://squidfunk.github.io/mkdocs-material/

**Comment by nvuillam** [comment]
> 

I have a script that splits the README into pages :)
