### ISSUE TITLE
Add repolinter support

### ISSUE THREAD

**Issue by janderssonse** [megalinter/megalinter#1428]
It would be super great to see repolinter support in MegaLinter. It is a tool for checking basic but standard healthfiles in an open source project. Comes with default rules that might need some minimizing though.

https://github.com/todogroup/repolinter

Phew, that's 3 feature linter requests in a few minutes. But with them MegaLinter would be THE ONE linter for my use case, and certainly many more. It is already a great project though, so many thanks for that, regardless of the future of any of the feature request added.

**Comment by nvuillam** [comment]
Thanks a lot for your support :)

MegaLinter v6 will have a REPOSITORY descriptor, repolinter could be a good candidate :)

Meanwhile... maybe you'd like to help by creating a [MegaLinter plugin](https://megalinter.github.io/latest/plugins/) to call it ? ^^

Examples of plugins:
- https://github.com/andreoliwa/nitpick/blob/develop/mega-linter-plugin-nitpick/nitpick.megalinter-descriptor.yml
- https://github.com/kpj/jupyfmt/blob/master/mega-linter-plugin-jupyfmt/jupyfmt.megalinter-descriptor.yml
