### ISSUE TITLE
ADD: gherkin-lint to the dotnet flavor

### ISSUE THREAD

**Issue by TommyE123** [megalinter/megalinter#1435]
Hello!
 
Congratulations on such a great project you have here and the work you have done!

Would it possible to consider adding **gherkin-lint** to the **dotnet** flavor?

There are many companies that use **SpecFlow** in their .NET tech stacks. It uses the **gherkin** language to write feature files to aid automation of code using C# and .NET methods.

https://specflow.org/

This would allow us to use a much smaller flavor and speed up pipelines etc.

Thanks
Tom

**Comment by nvuillam** [comment]
@TommyE123 it's on its way :)
Once CI passes, it will be available in MegaLinter beta version

**Comment by nvuillam** [comment]
@TommyE123 gherkin-lint is now available in MegaLinter dotnet flavor (beta version)

Please let me know if you have any issue with it :)

**Comment by TommyE123** [comment]
Thank you so much for implementing this feature so quickly. It's working perfectly as expected :-) 🥇

**Comment by nvuillam** [comment]
You're welcome :)
