### ISSUE TITLE
GitHub Actions commits reports to PR

### ISSUE THREAD

**Issue by estahn** [megalinter/megalinter#1473]
**Describe the bug**
The GitHub action doesn't clean artifacts before committing changed code thus all reports end up in the PR.

**To Reproduce**

Use the GitHub action and make a change that will be adjusted by megalinter.

**Expected behavior**

Reports should not end up in PR.

**Screenshots**
![image](https://user-images.githubusercontent.com/362174/168290548-26932083-a53a-40fb-bdc9-e1686acf8abc.png)

**Comment by Kurt-von-Laven** [comment]
Happy to accept a pull request, but I think the reason we haven't received this bug report previously is that there is generally an expectation that `report` be added to your `.gitignore` since MegaLinter may also be [run locally](https://megalinter.github.io/latest/mega-linter-runner/).

**Comment by nvuillam** [comment]
In v6 version to be released within the next weeks, default report file will be `megalinter-reports`, to avoid dir name collision if some repo already contains a `report` folder, but as @Kurt-von-Laven says, report folder must be added in .gitignore :)
