### ISSUE TITLE
Question: When running the Javascript Linter in GitLab CI I get an error with GitLab Runner

### ISSUE THREAD

**Issue by romelBen** [megalinter/megalinter#1482]
Hello! Enjoying MegaLinter with my projects. I wanted to ask a general question in regards to GitLab CI involvement: Is there a `quiet` mode in MegaLinter with outputting logs? The reason why I say this is because I receive an error:  `Job execution will continue but no more output will be collected.` which stops. The other method is to increase the size of the limit for the GitLab Runner but I was curious if MegaLinter has an option for not being `verbose`. 

Thanks again.

**Comment by nvuillam** [comment]
@romelBen I use MegaLinter with Gitlab Runners and that works well ^^
Did you define LOG_LEVEL=DEBUG ? If yes, just remove it and u'll have a lot less logs 

IF you already did that, you can try to add 
- `PRINT_ALL_FILES: false` (do not print the list of files for each linter)
- `CONSOLE_REPORTER: false` (no console linter log at all... but it seems quite radical ^^ )

**Comment by romelBen** [comment]
It looks much better. The thing is it just cannot continue.

```
Job's log exceeded limit of 4194304 bytes.
Job execution will continue but no more output will be collected.
```

I believe I just have too many errors for the Javascript flavor. Is there a more efficient method if you would know with Javascript linting @nvuillam?

**Comment by romelBen** [comment]
Oh, I'm terrible with reading. Thanks for this.

**Comment by nvuillam** [comment]
I'm glad it's all ok for your use case now :)
Thanks for your interest in MegaLinter and don't hesitate to ask next time you need to :)

**Comment by Hich69** [comment]
Hello nvuillam,
I found some of issues with limit up to 4mo, can you help me please, i juste want to build my projet containing a lot of jars. would you like to share your gitlab ci and conf.taml ?

**Comment by nvuillam** [comment]
@Hich69 please can you share a part of the log that takes so many place ? I'm sure we can find a solution:)

**Comment by Hich69** [comment]
> @Hich69 please can you share a part of the log that takes so many place ? I'm sure we can find a solution:)

hello @nvuillam,

Please consider this screenshot as attached, this represents my config.toml. To be honest, i find some troubles when restarting my gitlab-runner on windows and reset my output_limit. Can you help me please ?

![image](https://user-images.githubusercontent.com/11707485/179546038-76cb5066-2b5a-47eb-8c2a-b043560db9c8.png)

Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-jobclient/3.2.1/hadoop-mapreduce-client-jobclient-3.2.1.jar (86 kB at 5.1 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/hadoop/hadoop-yarn-client/3.2.1/hadoop-yarn-client-3.2.1.jar
Progr
Job's log exceeded limit of 4194304 bytes.
Job execution will continue but no more output will be collected.

**Comment by nvuillam** [comment]
@Hich69 I'm no expert in Gitlab runner :/
Did you try `PRINT_ALL_FILES: false` in your local `.mega-linter.yml`

**Comment by Hich69** [comment]
hello @nvuillam, 
Thanks for your response.
I setup my mega-linter on local computer.
I want to make a gitlab-ci which will build my project as .jar (mvn clean compile assembly:single) and deploy in local folder, can you help me to do this ?
I am trying to do this with your example in https://bytemeta.vip/repo/nvuillam/mega-linter/issues/1373 but i found some issues.

thanks in advance
