### ISSUE TITLE
MegaLinter "About" text is outdated.

### ISSUE THREAD

**Issue by melg8** [megalinter/megalinter#1497]
In GitHub repo of MegaLinter text of "About" is out of sync with description of actual main branch:
# About
![image](https://user-images.githubusercontent.com/16599015/170934330-005f0b86-ecb4-45ec-8b20-3c78afbcd8af.png)
# Description
![image](https://user-images.githubusercontent.com/16599015/170934451-acdec95d-68cf-490c-9ee6-32cebcd3c2db.png)

Number of supported languages and toolings formats increased from last update of "About" page.

**Comment by llaville** [comment]
See old issue #857

**Comment by nvuillam** [comment]
Just updated manually until we have something more automated ^^
