### ISSUE TITLE
Support for Local Plugin Files in Addition to HTTPS

### ISSUE THREAD

**Issue by jackheuberger** [megalinter/megalinter#1507]
**Is your feature request related to a problem? Please describe.**
I'm trying to write a custom Megalinter plugin that's defined in a private repository, meaning a GET request to the .yml definition cannot be made without setting access tokens in request headers.

**Describe the solution you'd like**
Support for file paths in the PLUGINS property within `.mega-linter.yml`. For example:

```yml
PLUGINS:
  - "<private_repo_submodule>/mega-linter-plugin-xxx/xxx.megalinter-descriptor.yml"
```

**Describe alternatives you've considered**
Support for the `file://` protocol. For example:

```yml
PLUGINS:
  - file://<pwd>/mega-linter-plugin-xxx/xxx.megalinter-descriptor.yml
```

**Additional context**
I would be willing to work on this. Thanks!

**Comment by nvuillam** [comment]
@jackheuberger i'd be glad to accept such PR :)
