### ISSUE TITLE
Project's website homepage blocked and flagged as fishing by Avast

### ISSUE THREAD

**Issue by echoix** [megalinter/megalinter#1555]
**Describe the bug**
To my surprise, the project's homepage, `https://megalinter.github.io/latest/` is marked and flagged as fishing by my Antivirus, Avast.

**To Reproduce**

1. Use a computer with Avast antivirus (free) installed
2. Go to `https://megalinter.github.io/latest/` on your browser.
3. See that the page can't load in Chrome.
4. See in the Avast antivirus application the explanation.

**Expected behavior**
The website can be accessed normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/27212526/175544956-209ecb07-2c20-4494-ad67-8d48f3b4f721.png)
![image](https://user-images.githubusercontent.com/27212526/175545116-02218500-4404-44b0-820d-f479c30a3219.png)
![image](https://user-images.githubusercontent.com/27212526/175551215-107a0100-5f67-4788-a93c-38aae21a3e5b.png)

**Additional context**
This should be a false positive, but I wonder what changes could have caused this.

**Comment by echoix** [comment]
I've looked up and refreshed the VirusTotal scan, and other web tools, and nothing was really flagged as such.
`https://www.virustotal.com/gui/url/fa883a51400ccf388d763e32cc3dc0d72072675a634d44e3bfef4fc26fd819d0/detection`
![image](https://user-images.githubusercontent.com/27212526/175547299-b54069ef-fdac-4d7c-9bc8-f89b8215e5ba.png)

`https://sitecheck.sucuri.net/results/https/megalinter.github.io/latest/`
![image](https://user-images.githubusercontent.com/27212526/175548091-d584d77f-7995-4238-8f68-6d1be1717b85.png)


`https://quttera.com/detailed_report/megalinter.github.io`
![image](https://user-images.githubusercontent.com/27212526/175547424-e2d2700b-8407-4b8f-8b61-45ffd96723ba.png)


However, in the VirusTotal links tab, I saw something unexpected, `https://www.ox.security/`, that is a protected webpage, that securi couldn't scan (401)
![image](https://user-images.githubusercontent.com/27212526/175548519-4fde3872-ee7c-4d2c-a5af-7de39e724851.png)
`https://sitecheck.sucuri.net/results/https/www.ox.security`
![image](https://user-images.githubusercontent.com/27212526/175549156-7039376b-ebec-4342-bcc6-377fbeb011f7.png)

I still followed up and filled out an Avast false positive form, but writing in the description I'd like some more information, that I'd probably never get anyways.
https://www.avast.com/false-positive-file-form.php

**Comment by nvuillam** [comment]
https://twitter.com/NicolasVuillamy/status/1534657667930652672

I know :(

**Comment by nvuillam** [comment]
Nope :/
Please let us know if Avast answers about their illogic block :)

**Comment by echoix** [comment]
I got an (automated) email from avast saying they cleared the reputation. 


> # #16050261 - Avast: Report a URL https://megalinter.github.io/latest/

Hello, 

Thank you for reporting this false positive.

We have now cleared its reputation in our database based on the findings and removed the detection. This change may take up to 24 hours to take full effect. Please accept our apology for the inconvenience caused.

If the detection persists after 24 hours, update the virus database in Avast anti-virus and reply to this email with the attached files:
1.Take a screenshot of the Avast detection dialog (Threat Secured pop-up with See details - displayed at the bottom).
2.Take a screenshot of the Avast virus database (open Avast antivirus and go to Menu > About).
We hope you have a nice day and stay safe online.

**Comment by echoix** [comment]
And I confirm I can open the website normally on my computer that had the issue initially.
