### ISSUE TITLE
Ability to give `megalinter` container an arbitrary name

### ISSUE THREAD

**Issue by dmitri-trofimov** [megalinter/megalinter#1557]
**Is your feature request related to a problem? Please describe.**
As a `megalinter` user on Windows I'd like to have an ability to run `megalinter` and supply a name to the Docker container it runs in so that I have less random container names in my Docker Desktop application.

**Describe the solution you'd like**
By looking at the `megalinter` runner code, it seems quite easy to add an option like `--containername` and pass it to Docker `docker ... --name <containername>`. I can try and create a PR for that.

**Describe alternatives you've considered**
I don't know of any alternatives.

**Additional context**
When a Docker container is run, it is given a random name (`redesigned-train` or `quantum-fish`...). Although I am not sure if this happens on Linux machines, it definetly happen on Windows in Docker Desktop. It also saves the containers, and after a few runs you get a list of many random looking containers in the list. I'd much rather prefer havin only one line corresponding to the `megalinter`.

![image](https://user-images.githubusercontent.com/46350232/175566231-d473e419-8c8e-4a84-b321-95004634fd78.png)

**Comment by Kurt-von-Laven** [comment]
Yes, this also happened on Linux, so thank you for the fix!
