### ISSUE TITLE
When `--containername` option is used, the container isn't given the specified name

### ISSUE THREAD

**Issue by dmitri-trofimov** [megalinter/megalinter#1560]
**Describe the bug**
Previously I crated a feature request (#1557) followed by a pull request (#1558) to allow naming of MegaLinter Docker container. Unfortunatlly I didn't test it well, so the feature doesn't actually work (although it doesn't break anything).

**To Reproduce**

1. Execute a command `npx mega-linter-runner@5.15.1-beta202206241616.0 --containername=TEST` on any projet
2. When done (or when it's still runnning) execute `docker ps -a`
3. Actual result: there is a container with image name `megalinter/megalinter:v5` but the container name is random (expected `TEST`).

**Expected behavior**
Expected to see a a container with image name `megalinter/megalinter:v5` with container name `TEST`.

**Additional context**
The `5.15.1-beta202206241616.0` version is the one that got cretaed when #1558 was merged to `main`. I have the fix coming, will create a PR soon.

**Comment by nvuillam** [comment]
Maybe you could add such option to your current pending pull request #1561 ? :)

**Comment by Kurt-von-Laven** [comment]
Sorry, which option are we discussing?

**Comment by nvuillam** [comment]
I was tired yesterday, nevermind ^^
Let's wait for the fix ^^
