### ISSUE TITLE
Add C++ and CMake linters

### ISSUE THREAD

**Issue by vkucera** [megalinter/megalinter#478]
Hi, thanks for the great tool!

Could you please add linters for C++ and CMake?

* C++:
  * [`clang-format` + `git-clang-format`](https://github.com/llvm-mirror/clang/tree/master/tools/clang-format) 
* CMake (`CMakeLists.txt`, `*.cmake` files):
  * [`cmake-format` + `cmake-lint`](https://pypi.org/project/cmake-format/)

If the formatted files could also be pushed, as for the other linter fixes, that would be perfect.

Cheers,
Vít

**Comment by nvuillam** [comment]
That's a great idea , and if the tools you name can format/fix it can be pushed :)
I can implement that someday, or maybe another contributor, or even you ? :)

**Comment by nvuillam** [comment]
not stale

**Comment by stepancheg** [comment]
I care about C++, and not much about CMake. Generally these things are related, but independent so perhaps should be discussed in separate issues.

* How to install it (`clang-format`)

This `Dockerfile` generated staticically linked 4Mb `clang-format` binary.

```docker
################################################################################
# Build the clang-format binary ################################################
################################################################################
FROM alpine:3.14.0 as clang-format-build

######################
# Build dependencies #
######################
RUN apk add --no-cache \
    build-base \
    clang \
    cmake \
    git \
    ninja \
    python3

#############################################################
# Pass `--build-arg LLVM_TAG=master` for latest llvm commit #
#############################################################
ARG LLVM_TAG
ENV LLVM_TAG llvmorg-12.0.1

######################
# Download and setup #
######################
WORKDIR /tmp
RUN git clone --branch ${LLVM_TAG} --depth 1 https://github.com/llvm/llvm-project.git
WORKDIR /tmp/llvm-project

#########
# Build #
#########
WORKDIR /tmp/llvm-project/llvm/build
RUN cmake -GNinja -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_BUILD_STATIC=ON \
    -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ .. \
    && ninja clang-format
```

* How to call it in lint mode
* How to call it in format / fix mode

`clang-format file.cpp` prints the reformatted file to stdout. It reads `.clang-format` config file in the file directory or any parent directory.

The lint output should be the diff between the original file and reformatted. Can be generated with the script:

```sh
#!/bin/sh
#
# run `clang-format` and output the diff between the file and reformatted version

die() {
  echo "$@" >&2
  exit 1
}

test "$#" -eq 1 || die "usage: $0 <file>"

# Print repo-relative path in the diff header.
# Assuming current directory is the repository root.
label=$(realpath --relative-to . "$1")

clang-format "$1" | diff -u --label "$label" "$1" --label "$label.expected" -
# `diff` exits with non-zero code on non-empty diff
```

* Example of a valid file
* Example of invalid file

Assuming default `.clang-format` config file.

Bad file:

```
void  *   *   f();
```

Good file:

```
void **f();
```

**Comment by nvuillam** [comment]
@stepancheg that's great, thanks for the detailed info , I'll try to use all that in a PR :)

**Comment by vkucera** [comment]
Hi @stepancheg @nvuillam , I am wondering whether this has been followed up.

**Comment by nvuillam** [comment]
Not done yet, but it should be present in MegaLinter I agree, let's reopen the issue :)

**Comment by vkucera** [comment]
Hi @stepancheg @nvuillam , sorry if I missed it, I am wondering whether there has been any progress on this.

**Comment by vkucera** [comment]
I think this issue should stay opened, as CMake is still not supported.

**Comment by nvuillam** [comment]
Agreed.... but we need help to write the PRs :)

Anyone interested ? :)
