### ISSUE TITLE
Add missing Bandit config file and rules path options

### ISSUE THREAD

**Issue by CAM-Gerlach** [megalinter/megalinter#679]
**Is your feature request related to a problem? Please describe.**

I am unable to configure Mega-Linter to recognize my existing repository-root Bandit config file (`.bandit.yml`), either by manually specifying the path to it, or by using the `LINTER_DEFAULT` option, as the relevant `PYTHON_BANDIT_CONFIG_FILE` config variable is missing. Therefore, Mega-Linter reports errors I've ignored there. Furthermore, `PYTHON_BANDIT_RULES_PATH` is not present as well; these two config variables exist for every other linter I could find, but not [Bandit](https://nvuillam.github.io/mega-linter/descriptors/python_bandit/). I confirmed they aren't just undocumented, as I tested adding them and Bandit's behavior didn't change.

As a result, given the duplication that would occur with maintaining two different config files for the same tool at two different paths and filenames, I've unfortunately had to refrain from running Bandit with Mega-Linter until this issue is resolved.

Presumably related to PR #533 .

**Describe the solution you'd like**

Add the two relevant config file path related variables, like all the other linters have.

**Describe alternatives you've considered**

Not adding the variables; there appears to be no clear motivation for this given all the other linters have them and bandit has a config file like all the others, so it would only make sense to have them as well.

**Additional context**

Thanks for your consideration!

**Comment by nvuillam** [comment]
True, i forgot to define a default config file name, that's what lead to the missing features + the missing variables in auto-generated doc :)

PR in progress

**Comment by CAM-Gerlach** [comment]
Thanks @nvuillam !

**Comment by nvuillam** [comment]
Released in latest/insiders, please can you confirm that it's ok now ?

Note: this [CI job](https://github.com/nvuillam/mega-linter/runs/3404311592?check_suite_focus=true) must be completed before testing is available with latest/insiders tag

**Comment by CAM-Gerlach** [comment]
Hey @nvuillam , thanks for your quick work on this! Unfortunately it doesn't seem to have worked all the way, though its quite possible I did something wrong. I set the action to `uses: nvuillam/mega-linter@insiders` as the Readme instructs, and I could see in the build output that the latest builds were getting pulled and I verified #680 is now fixed, and I'm also no longer getting an error due to the config file being incorrect and having a spurious option. However, the option does not appear to be honored, as I  nevertheless appear to be getting the same set of bandit errors (lots asserts in my tests, plus `subprocess.run()` without `shell=True`) that my `.bandit.yml` silences and my other local and CI runs of bandit don't pick up. You can check out what I have so far on r-spacex/submanager#11 ... Let me know if there's something else I should try. Thanks!

**Comment by nvuillam** [comment]
Indeed , `- Rules config: identified by [bandit]` indicates that there is no call to --config .bandit.yml

Please could you add LOG_LEVEL: DEBUG in your .mega-linter.yml config file ?

This will output veru chatty logs, but within them it will show the exact calls to bandit with arguments , so maybe from that we can see what's wrong

**Comment by CAM-Gerlach** [comment]
Sure, done as requested. 

[Pretty](https://github.com/r-spacex/submanager/pull/11/checks?check_run_id=3452003001) and [raw](https://pipelines.actions.githubusercontent.com/xUxQtX8oFzR79wGECSxUVUDUvLMKijrW0tyyYRyNZ26vg6vWln/_apis/pipelines/1/runs/232/signedlogcontent/4?urlExpires=2021-08-28T21%3A33%3A10.6648058Z&urlSigningMethod=HMACV1&urlSignature=ObWn2DdKljjqCPfVPLZdsVvqFMQoSIcePg%2F3bX%2Bthcg%3D) format logs on r-spacex/submanager#11 .

Looks like nothing is being passed to the bandit command except for the executable name and the list of files:

```bash
bandit] command: ['bandit', '/github/workspace/setup.py', '/github/workspace/src/submanager/__init__.py', <SNIP> '/github/workspace/tools/enable_praw_typehints.py', '/github/workspace/tools/generate_requirements_files.py']
```

**Comment by CAM-Gerlach** [comment]
BTW, I'm assuming the secretlint hit is due to a log file that the debug mode created? It didn't appear in the last run and it doesn't look like any actual file I have checked into the repo.

**Comment by CAM-Gerlach** [comment]
This is still an issue. Hey @nvuillam , any updates or anything else you need from me? Thanks!

**Comment by CAM-Gerlach** [comment]
Bump

**Comment by CAM-Gerlach** [comment]
Seems like the unstale action [failed](https://github.com/megalinter/megalinter/actions/runs/1523875770) @nvuillam

**Comment by nvuillam** [comment]
a loooooooooot on my plate these days, sorry :/

**Comment by llaville** [comment]
I'll help on this report ! Preparing a PR ...

**Comment by llaville** [comment]
PR failed with strange error : **Unable to get version for linter [v8r]** https://github.com/megalinter/megalinter/runs/4379776756?check_suite_focus=true#step:15:133

**Comment by llaville** [comment]
In the meantime, @CAM-Gerlach if you want to have a look and test upcoming version with `docker pull megalinter/megalinter:test-llaville-bandit_config`, I'll glad to hear your feedbacks !

**Comment by nvuillam** [comment]
@llaville v8r released a new version which is crashing on our image, so I downgraded it for now until we find what is crashing and why ^^ (maybe there is a debug to do on v8r, but i can't post an issue just saying "it crashes" :p )

**Comment by CAM-Gerlach** [comment]
> a loooooooooot on my plate these days, sorry :/

No worries man, I'm with you there—you gotta take care of yourself first. Especially when you're already providing an awesome free service to the whole community which is very very much appreciated :heart: 

> In the meantime, @CAM-Gerlach if you want to have a look and test upcoming version with docker pull megalinter/megalinter:test-llaville-bandit_config, I'll glad to hear your feedbacks !

Hey @llaville , thanks so much! I unfortunately don't have Docker set up on my current box, but if you can get it pushed to `nvuillam/mega-linter@insiders` I can test it for real on r-spacex/submanager#11 as I've tested the previous iterations

**Comment by nvuillam** [comment]
@CAM-Gerlach thanks :)

> Hey @llaville , thanks so much! I unfortunately don't have Docker set up on my current box, but if you can get it pushed to nvuillam/mega-linter@insiders I can test it for real on r-spacex/submanager#11 as I've tested the previous iterations

We are in v5 now, the beta version is `megalinter/megalinter:beta` :) cf https://megalinter.github.io/beta/#v4-versus-v5

You shoud upgrade to V5 using `npx mega-linter-runner --upgrade` :)

**Comment by CAM-Gerlach** [comment]
Nice, thanks! Will do that r-spacex/submanager#11 as well (though might have to do the ole' sync from my Linux box to my dev box trick to get `mega-linter-runner` to work, since the `yeoman` bug apparently still isn't fixed).

**Comment by nvuillam** [comment]
You can also just replace nvuillam/megalinter@insiders by megalinter/megalinter@beta :)

**Comment by CAM-Gerlach** [comment]
Bad news @nvuillam @llaville , unless I'm doing something wrong, it looks like its still not working, as its still not picking up my `.bandit.yml` config file and thus still raising lots of errors I've silenced. I've enabled debug mode and tried both `LINTER_DEFAULT` and `.bandit.yml` for the `PYTHON_BANDIT_CONFIG_FILE` with no luck.

From the linter default run: [mega-linter.log](https://github.com/megalinter/megalinter/files/7639283/mega-linter.log) [ERROR-PYTHON_BANDIT.log](https://github.com/megalinter/megalinter/files/7639289/ERROR-PYTHON_BANDIT.log)

From the run explicitly specifying the `.bandit.yml` config file:
[mega-linter.log](https://github.com/megalinter/megalinter/files/7639324/mega-linter.log)
[ERROR-PYTHON_BANDIT.log](https://github.com/megalinter/megalinter/files/7639326/ERROR-PYTHON_BANDIT.log)
 
The thing is, when I explicitly pass the config file, it gets passed with what looks like the correct arg, with the correct path to the config file (which matches the file found to check for other linters) and it says "Using config file PATH TO IT" in the logs, yet it still shows all the errors. I ran the same command locally, just with modified paths, and it works fine and shows that it scanned the files with no errors found. So I'm baffled as to what's going on.

**Comment by llaville** [comment]
@CAM-Gerlach I'm sorry but I disagree with you. I've just look on your log files provided, and I see that MegaLinter found a `.bandit.yml` in `/github/workspace`

- in `ERROR-PYTHON_BANDIT.log` line 11 --  `[main]	INFO	using config: /github/workspace/.bandit.yml`
- in `mega-linter.log` lines 108 to 110
```
Listing all files in directory [/github/workspace], then filter with:
Root dir content:
- /github/workspace/.bandit.yml
```

**Comment by llaville** [comment]
Config file finding strategy is defined on documentation https://megalinter.github.io/latest/descriptors/python_bandit/
A little remember
![megalinter github io_latest_descriptors_python_bandit](https://user-images.githubusercontent.com/364342/144469070-01331ed9-3e52-4cf0-9ef1-3bf940cc229a.png)

In your logs, as you've not defined a specific RULES_PATH, default strategy is then applied

**Comment by CAM-Gerlach** [comment]
> I've just look on your log files provided...

> In your logs, as you've not defined a specific RULES_PATH, default strategy is then applied

I'm a little confused what specifically you "disagree" with, sorry, since this is exactly as I explained above:

> when I explicitly pass the config file, it gets passed with what looks like the correct arg, with the correct path to the config file (which matches the file found to check for other linters) and it says "Using config file PATH TO IT" in the logs, yet it still shows all the errors. I ran the same command locally, just with modified paths, and it works fine and shows that it scanned the files with no errors found. 

The config file path arg is getting passed, Bandit is seemingly picking it up, its the correct path, yet the config isn't applied and all the errors are still shown, whereas this doesn't happen locally.

In any case, after some more deeper sleuthing, I've managed to reproduce it locally and figure out exactly what is going on. There are two issues:

* Mega-linter is passing absolute instead of relative paths to Bandit. This makes Bandit not apply the exclude paths correctly, so errors show up in the files that I've excluded (in this case, `assert_used` in the `tests/`). I could use Mega-Linter's regex filter to exclude these files, but this would exclude them completely from all Bandit checks, rather than just the one check, which is not desirable and not a general solution to the problem, and furthermore users expect Bandit excludes to be respected. The real solution is to either have Mega-Linter pass relative paths to Bandit, or open an issue with Bandit asking them about this behavior and if it can be changed. The latter might seem better, but they might have reasons for it, and their release cadence has been on a roughly ≈yearly basis lately, so it means we're still stuck with this issue for a long time. @nvuillam , thoughts?

* The config file is never found if using `LINTER_DEFAULT`, due to the explicit file paths being passed (relative or absolute) as documented in PyCQA/bandit#332 . That seems to be more definitively a Bandit issue, and there's not much Mega-Linter can do about that without a significant change in its architecture. Might be worth a note in the docs, though.

**Comment by nvuillam** [comment]
Do you mean it could be ok if config file path would be sent a relative and not absolute ?

**Comment by CAM-Gerlach** [comment]
Sorry I was unclear—I meant the paths to the files to check; I tested the config file path being relative or absolute and that didn't have an effect, only the actual files passed as arguments to `bandit`. That's why I wasn't seeing this issue locally or running the checker via Pre-Commit, because those methods all passed relative paths.

**Comment by nvuillam** [comment]
What if bandit was called in "project" mode (meaning  not with the list of files, but with the main directory) ?

**Comment by nvuillam** [comment]
( to see if it works, you can directly force it into your config with : `PYTHON_BANDIT_CLI_LINT_MODE: project` in your .megalinter.yml file )

**Comment by CAM-Gerlach** [comment]
Okay, so for that to work, the invocation would need to be `bandit -r . -c <CONFIG_PATH>` rather than the `bandit -c <CONFIG_PATH>` is currently per the logs; the current directory needs to be specified explicitly, and without `-r` Bandit will simply skip directories instead of recursing inside them (one of Bandit's rather UX-unfriendly default behaviors; another being not looking for a config file at all by default and requiring one be specified explicitly, so `LINTER_DEFAULT` basically just tells Bandit to not use a config file at all).

However, even that runs into more Bandit issues, as Bandit isn't matching the exclude paths correctly; a literal `.` has to be included (i.e. `skips: ['./tests/*']`, not `skips: ['tests/*']` or they don't match... but then that means that the Bandit Pre-Commit hook stops excluding them, since it passes them without the `.` prepended. Seems the real problem is that Bandit is globbing on literal path strings without normalizing/resolving them first; I can open an issue over there, but who knows when that will get addressed and merged and a new Bandit release cut. So if its possible to include a `relativepath` CLI mode or similar, that would be the quickest fix to get Bandit working with Mega-Linter, at least for now.

**Comment by nvuillam** [comment]
+ `PYTHON_BANDIT_ARGUMENTS: ["-r","."]` ? :)
