### ISSUE TITLE
PR comments reporter: Add support for other hosting services (e.g. Bitbucket)

### ISSUE THREAD

**Issue by GordonJess** [megalinter/megalinter#729]
One of the best features of this plugin is unfortunately only available to those using Github.  In my case, I'd love to see support for posting the result table to Bitbucket Server.

Would also be nice to be have 'file line comments' which highlight the issues found in the code.

**Comment by nvuillam** [comment]
I'm currently implementing such evolution for Gitlab comments, so it should be ok to manage it also on bitbucket

But as I don't have any bitbucket repo, would you be ok to test Bitbucket integration on an alpha version when it will be done ?

Or even make a PR like [this one](https://github.com/nvuillam/mega-linter/pull/732) ? :) ( basically, all would work with a new class BitbucketCommentReporter.py )

**Comment by GordonJess** [comment]
Excellent news.  I can test it, no problem.  If I can find some time before that I will try make a PR for it.

**Comment by nvuillam** [comment]
Please can you try with docker image nvuillam/mega-linter:alpha ? :)

**Comment by nvuillam** [comment]
Hmmm sorry, it's gitlab version, i've not done bitbucket yet, false alert ^^

**Comment by GordonJess** [comment]
> Would also be nice to be have 'file line comments' which highlight the issues found in the code.

A "Code Insights" report could be an even better way to report the linter result:
https://developer.atlassian.com/server/bitbucket/how-tos/code-insights/

This would allow merging of the PR to be blocked if the result does not meet certain standards :-)
