### ISSUE TITLE
v8r: Associate specific schema for files matching a glob pattern

### ISSUE THREAD

**Issue by GordonJess** [megalinter/megalinter#730]
v8r allows specific schemas to be specified for a file, by url or path.  I'd like to be able to configure which schema should be used to validate certain files against.

e.g.
```.yml
YAML_V8R_SCHEMA_CONFIG: 
  - "https://json.schemastore.org/geojson"
      - "**/feature.geojson"
  - "path/to/custom_schema.json": 
      - "**/my_file.yaml"
      - "**/my_file.yml"
```

**Comment by nvuillam** [comment]
I would manage that by defining a custom linter class for v8r, but it would be less messy if v8r was updated :)

Let's wait for the feedback of https://github.com/chris48s/v8r/issues/108

**Comment by nvuillam** [comment]
According for the reply, you can do the following:

Create a file **schemaCatalog.json** at the root of your workspace

```json
{ "$schema": "https://json.schemastore.org/schema-catalog.json",
  "version": 1,
  "schemas": [
               { "name": "geojson",
                 "description": "geojson",
                 "url": "https://path.to.your.schema.json",
                 "fileMatch": ["*.geojson"] 
                },
               { "name": "custom",
                 "description": "custom",
                 "url": "https://path.to.your.other.custom.schema.json",
                 "fileMatch": ["*.custom.json"] 
                },
 ] 
}
```

Then, define in your **.mega-linter.yml** file and it should work :) ( if not, please can you post the log with `LOG_LEVEL: DEBUG` ?

```yaml
YAML_V8R_ARGUMENTS: -c schemaCatalog.json
```

**Comment by GordonJess** [comment]
Hi @nvuillam,

Many thanks for the suggestion.  Unfortunately this method only seems to work for URLs.  I also have some private schemas that I don't necessarily want to share on the schemastore.  I'd also need to be able to provide a path to a local schema.

**Comment by nvuillam** [comment]
Let's wait the reply again :p 

https://github.com/chris48s/v8r/issues/110

**Comment by nvuillam** [comment]
Stale but not so much... waiting for v8r to implement functionality ^^
