### ISSUE TITLE
How to generate HTML report for npm-groovy-lint?

### ISSUE THREAD

**Issue by GordonJess** [megalinter/megalinter#741]
Before I can get feedback direct to my PRs (#729), I want to present the `npm-groovy-lint` results in Jenkins in a clear and easy to understand format.  I'm looking at the [Warning Next Generation Plugin](https://www.jenkins.io/doc/pipeline/steps/warnings-ng/) which can visualise CodeNarc reports, show trend, and link to the problematic lines.

To generate the HTML report for parsing, I am adding the following to my `.mega-linter.yml` configuration, as per the [npm-groovy-lint documentation](https://www.npmjs.com/package/npm-groovy-lint):

```yaml
GROOVY_NPM_GROOVY_LINT_ARGUMENTS:
  - "-o 'tmp/lint/report/groovyLintResults.html'"
```

But I am getting the following error:

> [npm-groovy-lint] test/pipelineSpec.groovy - ERROR - 1 error(s)
> --Error detail:
> Parse options error: Value for 'output' of type 'String' required.
> 
> â�Œ Linted [GROOVY] files with [npm-groovy-lint]: Found 2 error(s) - (1.22s)

I have also tried several variations with no success:

```yaml
  - "-o \"tmp/lint/report/groovyLintResults.html\""
  - -o tmp/lint/report/groovyLintResults.html
  - -o "./tmp/lint/report/groovyLintResults.html"
  ...
```

**Comment by nvuillam** [comment]
Can you try one line by argument ? :)

```yaml
- o
- ./tmp/lint/report/groovyLintResults.html
```

**Comment by GordonJess** [comment]
> Can you try one line by argument ? :)
> 
> ```yaml
> GROOVY_NPM_GROOVY_LINT_ARGUMENTS:
> - o
> - ./tmp/lint/report/groovyLintResults.html
> ```
> 
> or
> 
> ```yaml
> GROOVY_NPM_GROOVY_LINT_ARGUMENTS: ["-o","./tmp/lint/report/groovyLintResults.html"]
> ```

Thanks again for the super quick feedback, much appreciated!

I can now generated the report but I still have a few issues:

- #712
- the report is generated for each file, overwriting the previous output and leaving only the report for the last file that was linted.
- the report references files with prefix 'tmp/lint/', so they cannot be found in the Jenkins workspace
  - I tried to change the working directory to /tmp/lint and overwrite npm-groovy-linter's '--path' argument with '.', but no success.  The debug output show that `--path` is not overwritten, but both are supplied:
```
[npm-groovy-lint] command: ['npm-groovy-lint', '--failon', 'info', '-o', './report/groovyLintResults.xml', '--path', '.', '--path ', '/tmp/lint/test', '--files ', '**/pipelineSpec.groovy', '-c', '/action/lib/.automation/.groovylintrc.json']
```
