### ISSUE TITLE
HTML entities in generated configuration

### ISSUE THREAD

**Issue by GrabCAD-Gary** [megalinter/megalinter#767]
**Describe the bug**
HTML entities are included in the generated configuration e.g.

```
VALIDATE_ALL_CODEBASE: ${{ github.event_name == &#39;push&#39; &amp;&amp;
```

and these break the GitHub action.

```
The workflow is not valid. .github/workflows/mega-linter.yml (Line: 48, Col: 34): Unexpected symbol: '&#39;push'. Located at position 22 within expression: github.event_name == &#39;push&#39; &amp;&amp; github.ref == &#39;refs/heads/master&#39;
```

**To Reproduce**

1. Generate a config file which includes the action using `npx mega-linter-runner --install`.
2. Check in.
3. Check the `Actions` tab.

**Expected behavior**
The action should not fail.

**Screenshots**
N/A

**Additional context**
You can work around the problem by simply replacing the entities with their normal equivalents.

**Comment by nvuillam** [comment]
Indeed !
I'll check that !

![image](https://user-images.githubusercontent.com/17500430/134921517-ed8f4479-375d-4ba9-a72c-736424658dad.png)
