### ISSUE TITLE
PMD as a general linter (for Java and other technologies)

### ISSUE THREAD

**Issue by bittner** [megalinter/megalinter#774]
I see that [PMD](https://pmd.github.io/) is seemingly integrated [for Salesforce projects](https://nvuillam.github.io/mega-linter/descriptors/salesforce_sfdx_scanner_lwc/) as the `SALESFORCE_SFDX_SCANNER_LWC` linter/descriptor.

For what I understand, PMD is a generic code analysis tool. It's most likely not specific to Salesforce, so what is the reason for having it integrated for [SFDX](https://developer.salesforce.com/tools/sfdxcli) only? Wouldn't it make sense to have PMD as a general linter for a large range of programming languages (and project types), not just Salesforce setups?

_Note that I'm neither deep into Salesforce nor PMD. So, sorry if my question is silly._

**Comment by nvuillam** [comment]
That would be great to have PMD for java too :)

Let's do that someday ! 

Maybe you're like to contribute ? ^^

**Comment by bittner** [comment]
Can you describe the process of adding a new linter as a plugin?

**Comment by nvuillam** [comment]
Everything is explained here, please let me know if you have questions :)

https://nvuillam.github.io/mega-linter/contributing/

**Comment by llaville** [comment]
Adding a new linter as plugin is very difficult (sorry to said that @nvuillam).
Current version allow only remote definition, what is a bit difficult to develop / debug. And there are also some issues.
I've begun to work on a contrib to allow local plugins too ... but I'd prefered recently to work on PHP family linters ;)

**Comment by nvuillam** [comment]
@llaville if you think a plugin is hard to add in Mega-Linter, you should try to see the difference when you try to add one in Super-Linter bash scripts :p 

Do you know you can add a plugin locally, and run test cases locally ?
Basically:
- update descriptor
- run bash build.sh (which will create test classes)
- run test class using VsCode or PyCharm ^^

**Comment by nvuillam** [comment]
Not stale :)
