### ISSUE TITLE
Option to disable 'validate all codebase' message

### ISSUE THREAD

**Issue by ChipWolf** [megalinter/megalinter#789]
**Describe the solution you'd like**
Option similar to `FLAVOR_SUGGESTIONS` but for this message: https://github.com/nvuillam/mega-linter/blob/5396e00f4290d0788e2d9ddeecaf26addcad185d/megalinter/reporters/GithubCommentReporter.py#L140-L144

**Describe alternatives you've considered**
Ignoring it

**Additional context**
Unnecessary message, I disabled the feature intentionally, I don't need to be reminded that it can be enabled

**Comment by nvuillam** [comment]
Good proposition :)

Would you like to make a PR with management of `VALIDATE_ALL_CODEBASE_SUGGESTION: false` ?

If would require an update in the python code (that you already found), + updating the doc (README.md) and the [JSON schema](https://github.com/nvuillam/mega-linter/blob/master/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json)

**Comment by ChipWolf** [comment]
> Good proposition :)
> 
> Would you like to make a PR with management of `VALIDATE_ALL_CODEBASE_SUGGESTION: false` ?
> 
> If would require an update in the python code (that you already found), + updating the doc (README.md) and the [JSON schema](https://github.com/nvuillam/mega-linter/blob/master/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json)

Alternatively, we consolidate all suggestions into `ENABLE_SUGGESTIONS` or something? Sure though, I'll write a PR

**Comment by nvuillam** [comment]
I like the ENABLE_SUGGESTIONS options, you can go for the PR :)

**Comment by brianpaden289** [comment]
Bump

**Comment by nvuillam** [comment]
@brianpaden289  > @ChipWolf  has some conflicts to manage ^^
