### ISSUE TITLE
Remove extraneous message on success

### ISSUE THREAD

**Issue by ChipWolf** [megalinter/megalinter#790]
**Describe the bug**
This message appears despite the run succeeding, there's two hyperlinks to the run in the body, this message is not necessary: https://github.com/nvuillam/mega-linter/blob/5396e00f4290d0788e2d9ddeecaf26addcad185d/megalinter/reporters/GithubCommentReporter.py#L133-L136

**To Reproduce**
1. Succeed a mega linter run
2. Observe two hyperlinks to the action run in the message body, one on the 'SUCCESS' message and the other on the message referenced above

**Expected behavior**
This message not to display on successful runs

**Comment by nvuillam** [comment]
Maybe just renaming into **See linter log details** ?

They are generated even when there are no errors

**Comment by ChipWolf** [comment]
> Maybe just renaming into **See linter log details** ?
> 
> They are generated even when there are no errors

This is true, but there are two links to the same log in the same message body
