### ISSUE TITLE
[v4.46] LINTER_CLI_LINT_MODE should not be available for some linter that not accept `project` mode

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#795]
**Describe the bug**
`jsonlint` does not accept the `project` mode (when trying to override it with `JSON_JSONLINT_CLI_LINT_MODE`)

**To Reproduce**

1. Have a repository with lot of JSON files to validate (For [example](https://github.com/llaville/php-compatinfo-db)) 1430 json files to scan in data folder
2. Switch to `project` mode for `jsonlint` in `.mega-linter.yml` config file : `JSON_JSONLINT_CLI_LINT_MODE: project`
4. See error as in screenshot

**Expected behavior**
An acceptance LINTER_CLI_LINT_MODE rule to forbid such situation

I've tried the project mode due to a perf issue with jsonlint in file mode : 1430 files analysed in 6 minutes

**Screenshots**

![jsonlint_project_mode](https://user-images.githubusercontent.com/364342/135403436-b24aa6de-a82f-455a-a0d4-0dd971960f06.png)

**Additional context**
Natively `jsonlint` with folder gave also error as follow : 

![jsonlint_folder](https://user-images.githubusercontent.com/364342/135403733-900171e8-e34c-4935-a190-c565f93a306c.png)

**Comment by nvuillam** [comment]
Doing that would require to define some available_cli_lint_modes on ALL linters ... :)

Maybe we could do something like 

if available_cli_lint_modes is defined on descriptor
then check cli_lint_mode
else let the user try what he/she wants, at his/her own risks 🤣

**Comment by llaville** [comment]
> 
> Maybe we could do something like
> 
> if available_cli_lint_modes is defined on descriptor then check cli_lint_mode 

👍 for a better shield even if it's requires more works 

> else let the user try what he/she wants, at his/her own risks 🤣

👎 having a strange error is worst whatever audience read report, and lose time before to know what really happens ! Even if its a quick solution (nothing to do)

**Comment by nvuillam** [comment]
Listing all cli lint mode would allow to detect the ones which are still with file whereas they could accept list of files, and improve default geberal performances ^^
Why not soleday if me or someone else wants have the time to do that ^^
