### ISSUE TITLE
Support Additional Output Formats (ie. JUNIT, SARIF)

### ISSUE THREAD

**Issue by AErmie** [megalinter/megalinter#805]
**Is your feature request related to a problem? Please describe.**
When using MegaLinter in CI, the output needs to be developer-friendly and easy to reference. Especially if there are a lot of errors that need to be addressed. 

**Describe the solution you'd like**
I would like native support for different output formats, including JUNIT, SARIF, and possibly HTML/PDF.

**Describe alternatives you've considered**
There are a few issues ([Report in JSON](https://github.com/nvuillam/mega-linter/issues/694) and [Support for JUNIT artifacts for results visualization](https://github.com/nvuillam/mega-linter/issues/538)) that provide alternative approaches like converting TAP files, but that is not always an option (ie. in self-hosted/shared environments that have limitations and restrictions on what can be installed on the build server).

**Additional context**
Here are a few tools that provide additional output formats (in case their approach can be easily retrofitted into MegaLinter):
- [Checkov](https://github.com/bridgecrewio/checkov)
- [TFSec](https://github.com/aquasecurity/tfsec)
- [KICS](https://github.com/Checkmarx/kics)
- [Trivy](https://github.com/aquasecurity/trivy)
- [Terrascan](https://github.com/accurics/terrascan)

**Comment by nvuillam** [comment]
Not stale :)
It will require a lot of work, probably be in v6, but should happen someday and bring MegaLinter to the next level ;)

**Comment by wesley-dean-flexion** [comment]
+1 to SARIF support

**Comment by nvuillam** [comment]
@wesley-dean-flexion SPOILER : With v6 (currently in alpha), there will be lots of new linters, often security oriented, and SARIF support managed for the linters that are able to produce it  (see ![](https://shields.io/badge/-SARIF-orange) icons ) :)

https://megalinter.github.io/v6-alpha/supported-linters/

**Comment by dgutson** [comment]
@nvuillam when is v6 expected to go out?

**Comment by nvuillam** [comment]
@dgutson I have to synchronize with a partner, but for the moment it is planned for mid/end of june :)

You are free to use v6 alpha at your own risk, but it's really an alpha version :D
