### ISSUE TITLE
Add a Regexp based customizable linter

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#828]
**Describe the solution you'd like**
I'd like to have in future versions of Mega-Linter, a regular expression based linter like [Goodcheck](https://github.com/sider/goodcheck)

**Describe alternatives you've considered**
Use [bash-exec](https://nvuillam.github.io/mega-linter/descriptors/bash_bash_exec/) linter, with more complex syntax ! 

See good first example to follow : https://sider.github.io/goodcheck/docs/rules#rule-target_blank-security-issue

**Comment by nvuillam** [comment]
It can be nice :)
But for the same use case, isn't SameGrep more popular ?

https://github.com/returntocorp/semgrep

**Comment by llaville** [comment]
@nvuillam I'm surprised to read that Goodcheck is include in PR 996 after your comment https://github.com/megalinter/megalinter/issues/828#issuecomment-939375479 about semgrep

**Comment by nvuillam** [comment]
i was offline in a plane... indeed ... maybe they can be complementary ?

**Comment by nvuillam** [comment]
GitLeaks is integrated in the future V6 :)
