### ISSUE TITLE
Can't Get Version of eslint-plugin-jsonc

### ISSUE THREAD

**Issue by Kurt-von-Laven** [megalinter/megalinter#845]
**Describe the bug**
Before running ESLint, Mega-Linter tries to log the version of eslint-plugin-jsonc and fails because it's unable to get the version.

**To Reproduce**

1. Run ESLint at Mega-Linter v4.46.0.

Sometimes `Unable to get version for linter [eslint-plugin-jsonc]` will appear in the logs. I haven't investigated when specifically this occurs, but I think it may happen when a linting error occurs?

**Expected behavior**
The version of eslint-plugin-jsonc is obtained successfully.

**Screenshots**
See [lines 50-52](https://github.com/nvuillam/mega-linter/issues/773#issuecomment-927156323).

**Additional context**
Please refer to the linked thread.

**Comment by llaville** [comment]
Because npm [is installed](https://github.com/nvuillam/mega-linter/blob/v4.46.0/Dockerfile#L66) as [APK package](https://pkgs.alpinelinux.org/contents?branch=edge&name=npm&arch=x86&repo=main)

We can use absolute path `/usr/bin/npm` in [cli_executable_version](https://github.com/nvuillam/mega-linter/blob/v4.46.0/megalinter/descriptors/json.megalinter-descriptor.yml#L99)

Here are what we can get 
```
Linter version command: ['/usr/bin/npm', 'list', 'eslint-plugin-jsonc']
Linter version result: 0 /
└── eslint-plugin-jsonc@1.7.0 



### Processed [JSON] files
- Using [eslint-plugin-jsonc v1.7.0] https://ota-meshi.github.io/eslint-plugin-jsonc/

```

**Comment by llaville** [comment]
> 
> 
> Would it also work to use `/usr/bin/env npm` in case npm moves upstream or Mega-Linter installs npm differently in the future?

Yes it did; 👍 to adopt `/usr/bin/env npm` in [cli_executable_version](https://github.com/nvuillam/mega-linter/blob/v4.46.0/megalinter/descriptors/json.megalinter-descriptor.yml#L99), unless @nvuillam is not agree

**Comment by llaville** [comment]
BTW, @nvuillam I recommand also to adopt it (`/usr/bin/env npm`) for [.automation/build.py:generate_version](https://github.com/nvuillam/mega-linter/blob/v4.46.0/.automation/build.py#L2049)

That will allows to reduce Bandit linter errors by 1; See following report 

```
>> Issue: [B607:start_process_with_partial_path] Starting a process with a partial executable path
   Severity: Low   Confidence: High
   Location: /github/workspace/.automation/build.py:2048
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b607_start_process_with_partial_path.html
2047	    cwd_to_use = os.getcwd() + "/mega-linter-runner"
2048	    process = subprocess.run(
2049	        ["npm", "version", "--newversion", RELEASE_TAG],
2050	        stdout=subprocess.PIPE,
2051	        universal_newlines=True,
2052	        cwd=cwd_to_use,
2053	        shell=True,
2054	    )
```

**Comment by llaville** [comment]
Of course, to keep it working with `cli_executable_version: "/usr/bin/env npm"` syntax, 

```
Linter version command: ['/usr/bin/env', 'npm', 'list', 'eslint-plugin-jsonc']
Linter version result: 0 /
└── eslint-plugin-jsonc@1.7.0 extraneous



### Processed [JSON] files
- Using [eslint-plugin-jsonc v1.7.0] https://ota-meshi.github.io/eslint-plugin-jsonc/
```

`megalinter/Linter.py: build_version_command()` code need to be modified a little bit. 
```
diff --git a/megalinter/Linter.py b/megalinter/Linter.py
index 4f74bf5d..1f0d4333 100644
--- a/megalinter/Linter.py
+++ b/megalinter/Linter.py
@@ -878,7 +878,7 @@ class Linter:

     # Build the CLI command to get linter version (can be overridden if --version is not the way to get the version)
     def build_version_command(self):
-        cmd = [self.cli_executable_version]
+        cmd = self.cli_executable_version.split()
         cmd += self.cli_version_extra_args
         if self.cli_version_arg_name != "":
             cmd += [self.cli_version_arg_name]
```
That is BC with a single string (without blank)

**Comment by nvuillam** [comment]
Hmmm it can work, but we also need to make test class work on local windows env, so maybe we need something a little bit more complicated ^^

**Comment by llaville** [comment]
> 
> 
> Hmmm it can work, but we also need to make test class work on local windows env, so maybe we need something a little bit more complicated ^^

Could you explain us, how Windows users platform could be affected ? Don't we used Docker images (Linux Alpine distribution based)

**Comment by nvuillam** [comment]
Developers of Mega-Linter can be affected ^^
It's quite faster to run them directly individually than build docker image and run all tests ^^
![image](https://user-images.githubusercontent.com/17500430/137803213-1e1c53e6-c796-4d4b-b21f-8a3c13785da7.png)

**Comment by llaville** [comment]
I found a solution Linux/MacOS/Windows compatible for local testers.
I can't test it until tomorrow morning ... so wait for the contrib that should come shortly.

**Comment by llaville** [comment]
@nvuillam , @Kurt-von-Laven Any news about a fix for this issue ?

**Comment by nvuillam** [comment]
@llaville will #872 fix the issue ?

**Comment by llaville** [comment]
For me yes, but I'm still waiting your feedback about it and specially if its ok for you locally on windows.

**Comment by nvuillam** [comment]
I made a quick test on windows, it didn't crash, so I merged the PR :)
