### ISSUE TITLE
Rename .markdown-lint.json to .markdownlint.json

### ISSUE THREAD

**Issue by Kurt-von-Laven** [megalinter/megalinter#853]
**Describe the bug**
It would be best to name the templates after their defaults upstream to maximize Mega-Linter's compatibility with the linters it wraps.

**To Reproduce**

1. Compare [the upstream documentation](https://github.com/DavidAnson/markdownlint#config) to [Mega-Linter's Markdownlint template](https://github.com/nvuillam/mega-linter/blob/master/TEMPLATES/.markdown-lint.json).

**Expected behavior**
No configuration changes are needed to switch between running Markdownlint directly and via Mega-Linter.

**Additional context**
This will have the added benefit of causing [Schemastore](https://github.com/SchemaStore/schemastore/blob/31d43a19364287d1d505577d30c6c34d09af5bf1/src/api/json/catalog.json#L3622-L3633) to automatically check both Mega-Linter's template and the templates of downstream projects. I can't think of a way to do this that wouldn't be a breaking change, so I am proposing this for inclusion in v5 at earliest.

**Comment by nvuillam** [comment]
We can consider wrong naming of markdownlint.json as a bug (probably inherited from Super-Linter) , and i don't think many people has overridden it, so maybe it's not necessary mandatory to wait for V5 to fix that ^^
And to be honest, i'd like a V5 to have breaking changes more shiny than renaming a default config file :p

**Comment by Kurt-von-Laven** [comment]
That seems wise. I since realized that Mega-Linter already set this precedent with past config template renames.

**Comment by Kurt-von-Laven** [comment]
To head off any confusion, v5 has been released, but this hasn't been fixed yet. Refer to:
- [.markdown-lint.json](https://github.com/megalinter/megalinter/blob/45bbd4c4230bfe6c5a7da0f0b27b6e04e3834c0e/.markdown-lint.json)
- [TEMPLATES/.markdown-lint.json](https://github.com/megalinter/megalinter/blob/45bbd4c4230bfe6c5a7da0f0b27b6e04e3834c0e/TEMPLATES/.markdown-lint.json)
- [.automation/test/sample_project_fixes/.markdown-lint.json](https://github.com/megalinter/megalinter/blob/4e2663d84c816f196d99d805dd528c49edede607/.automation/test/sample_project_fixes/.markdown-lint.json)
- [our documentation](https://megalinter.github.io/latest/descriptors/markdown_markdownlint/)

I think this issue basically boils down to doing a global find-replace of both file contents and filenames.

@calexandre, I see the value of making `LINTER_DEFAULT` the default configuration file not only for Markdownlint, but for every linter. I could certainly believe there is some deeper consideration I am overlooking on that point, @nvuillam?

**Comment by nvuillam** [comment]
`LINTER_DEFAULT` is a legacy variable of Super-Linter, I'm not sure it's very wise to use it , as linters locally installed won't use it :/
I thnk that as we announced the renaming of markdown-lint.json into markdownlint.json we can apply it in a next minor release of V5 :)

**Comment by nvuillam** [comment]
Plz forget my remark about LINTER_DEFAULT, i made a mistake with LINTER_RULES_PATH :)

**Comment by Kurt-von-Laven** [comment]
If I understand correctly, ultimately, you would also support making `LINTER_DEFAULT` the default configuration file (and possibly eventually obviating it) for all linters?

**Comment by calexandre** [comment]
Just to be clear, this is my current `.mega-linter.yml` (i stripped most of the configuration):

```yaml
# Configuration file for Mega-Linter
# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation
(...)
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT
```

With the above in mind, is there any other recommendation for using the linter's defaults?
I don't agree that the default should be `.markdownlint.json`, as I use the `yaml` version...one could argue that the contrary also applies.
To fix this, I believe we should follow the linter's specification regarding the defaults - in the case of the `markdownlint` linter it supports multiple default flavors that go from `json` to `yaml` (and probably others) and I still feel that setting I'm using `LINTER_DEFAULT` should be the actual default, or am I missing anything?

**Comment by Kurt-von-Laven** [comment]
Right now, you do have to specify `LINTER_DEFAULT` manually as you have done. I agree that this should be the default, and I think @nvuillam does too if I interpreted his response correctly.

**Comment by nvuillam** [comment]
@calexandre I confirm @Kurt-von-Laven 's answer, you must specify `MARKDOWN_MARKDOWNLINT_CONFIG_FILE: LINTER_DEFAULT` in your configuration

An evoluton that we could do is to make possible to define config_file_name as a list and not as an unique config file name.
That way, the behavior would be : 
- browse repo to find config file name 1, config file name 2, config file name 3, etc...
- if not found, then use default config file provided by MegaLinter
