### ISSUE TITLE
[integration] Integrate Mega-Linter with Danger JS as an Danger plugin

### ISSUE THREAD

**Issue by ajhalili2006** [megalinter/megalinter#854]
**Is your feature request related to a problem? Please describe.**
I'm using Danger JS on GitLab to automate code review on merge requests, but the problem is I need to upload the `reports` directory as an artifact, get the artifact download URL + CI job URL through GitLab API and slap it to Danger JS as a message.

**Describe the solution you'd like**
Make these reports more native by creating a Danger JS plugin for Mega-Linter where creates a Markdown comment below the warnings, errors, and messages, similar to this:

---

|      | Fails |
| --- | --- |
| 🚫 |  mega-linter: Errors have been found during linting. Download it from your CI artifacts and manually copy-paste the fixed contents into your code or inspect the linter logs. |

|   | Warnings |
| --- | --- |
| ⚠️ | mega-linter: Warning has been found during linting. Download it from your CI artifacts and manually copy-paste the fixed contents into your code or inspect the linter logs. |

|   |  Messages |
| --- | --- |
| 📖 |  mega-linter: No errors or warnings have been found during linting. 

## Mega-Linter Report Summary

**Note**: Reports are available to download through <https://file.io/random-upload-id> and as artifacts of this project's CI provider.

| Descriptor | Linter | Files | Fixed | Errors | Elapsed Time |
| --- | --- | --- | --- | --- | --- |
| ❌ DOCKERFILE | hadolint | 2 | 12 | 15 | 34.6s |
| ✅ YAML | yamllint | 4 | | 0 | 60.3s |

<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

---

**Describe alternatives you've considered**
If a user or organization uses GitHub Actions as their CI and their code is usually maintained in GitHub, the [built-in comment reporter](https://github.com/nvuillam/mega-linter/blob/master/docs/reporters/GitHubCommentReporter.md) might be enough. In the case of GitLab repos, they may need to mirror the PR to a temporary fork of its GitHub mirror first then trigger a pull request which is painful to do since DIY DevOps is more chaotic to maintain than using just one DevOps platform instead and also the overhead of synchronizing branches and to switch context between GitHub and GitLab UI.

**Additional context**
Additional docs can be read at <https://danger.systems/js/usage/extending-danger.html> and <https://danger.systems/js/reference.html> for DSL reference.

**Comment by nvuillam** [comment]
That's a great idea, would you like to make a pull request ?
