### ISSUE TITLE
[CI] trivy timeout enhancement

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#856]
**Describe the bug**
CI and Docker images deployment, with Trivy vulnerability scanner end lot of time by timeout 

**Expected behavior**
Finish CI jobs

**Additional context**
Trivy-Action used in CI https://github.com/nvuillam/mega-linter/blob/master/.github/workflows/deploy-PROD.yml#L130-L138, and https://github.com/nvuillam/mega-linter/blob/master/.github/workflows/deploy-PROD-flavors.yml#L114-L122 is a bit outdated. V0.0.18 is related to aquasec/trivy:0.18.1 which is a bit outdated now (5 months ago)

Latest V0.2.0.1 is related to aquasec/trivy:0.19.2

BTW, you don't used either `timeout` or `cache-dir` options.
I suggest, after local tests to use the `cache-dir` option that will speed-up future execution especially in flavors context (multiple runs)

**Comment by nvuillam** [comment]
FYI, still trying to update to latest version :)

**Comment by llaville** [comment]
I close this issue, because you are working on new Security flavor (#1036)
