### ISSUE TITLE
Mega-Linter -> Let's be a team of maintainers for V5 :)

### ISSUE THREAD

**Issue by nvuillam** [megalinter/megalinter#860]
I created Mega-Linter during COVID, when I had a lot of available time :)

Since that, Mega-Linter became more and more used, meaning more and more Issues and PR submitted by the great Mega-Linter users community !

As I took a new job as CTO in Hardis Group, my available time have obviously been reduced a lot, and I think that to continue to provide a quality tool to open source community, Mega-Linter has to evolve from a "one single guy responsibility" to a more efficient "Team of Mega-Linter maintainers" , to avoid having issues with 2 weeks response time like it's happening more and more these days :)

The principles would be the following:
- To be a member of the team
  -  You must be an active contributor to Mega-Linter project
  - I must be in contact wiht you via LinkedIn & Twitter to try to make sure that you're not some hacker trying to hide backdoors ^^
  - [Watch the repository](https://github.com/nvuillam/mega-linter/watchers) to receive Issues & PR notifications
- Every member of the team can validate PRs
- In case of any doubt, he/she must highlight in comments to other members of the team to reach an agreement
- For the moment, I remain the only one generating official releases

Who would be interested ?

maybe @llaville @tpansino @Kurt-von-Laven ? :)

**Comment by nvuillam** [comment]
Migration (almost) complete :)

- Mainteners team: https://github.com/orgs/megalinter/teams/megalinter-maintainers (@Kurt-von-Laven )
- I also created a contributor team (you can directly create your sub-branches in the main repo , so have better CI, and access to "Quick build" option) (@llaville @tpansino :) )

**Comment by llaville** [comment]
> 
> Migration (almost) complete :)
> 

What a fast run ;-) And celebrate this new major version ! 
Hope CI will be more stable than previous and avoid to raise false positive like trivy timeout, tsqllint errors (just to notice some of them).   Don't be hurt @nvuillam its just my own feeling about this great project, what I still belive in.


>   I also created a contributor team (you can directly create your sub-branches in the main repo , so have better CI, and access to "Quick build" option) (@llaville @tpansino :) )

Thanks

**Comment by nvuillam** [comment]
I'm not hurt by reality, timeouts in trivy are boring, especially at the end of a 45 mn CI job :D 
And same as tsqllint (that I still saw today >_< >_< )

Probably than succeeding to upgrade to latest trivy may help... and about tsqllint I think i'll just add a hack

**Comment by Kurt-von-Laven** [comment]
I am excited to report that incremental mode works locally at `v5.0.1`! Really neat to experience all the optimizations you introduced running at maximum velocity on my laptop. It is indeed an order of magnitude faster provided that you skip jscpd, which inherently must run on all files in order to detect code duplication.

**Comment by nvuillam** [comment]
@Kurt-von-Laven that's great news dear go maintener, i'll probably never use mega Linter locally but i'm glad your updates allows our users and you to do so 😎📸

**Comment by Kurt-von-Laven** [comment]
You guessed it! I have been experimenting with one locally, and I feel that it's worth sharing soon.
