### ISSUE TITLE
markdownlint in mega-linter is no longer inheriting the configuration according to the official markdownlint configuration

### ISSUE THREAD

**Issue by calexandre** [megalinter/megalinter#875]
**Describe the bug**
According to the official markdownlint documentation, the configuration can be specified either with json or yaml, as stated in the documentation: https://github.com/DavidAnson/markdownlint/tree/main/schema

Such files must be named in the following dotfile format:
* `.markdownlint.yml` or `.markdownlint.yaml`
* `.markdownlint.json`
* `.markdownlint.jsonc`

Also, markdownlint will automatically look for these files in the repository root without the need to specify the location of the configuration manually, which is neat.

**Now, with the latest update of mega-linter**, this behaviour changed and is no longer inheriting the default configuration and we are required to either specify `.markdown-lint.json` or override the default configuration by setting the `MARKDOWN_MARKDOWNLINT_CONFIG_FILE` configuration.

**I believe that this is a step-back in terms of compatibility**, because mega-linter should at least work by default with the linter's defaults.

One way to mitigate this loss-of-compatibility would be to set the `MARKDOWN_MARKDOWNLINT_CONFIG_FILE` default to something that `markdownlint` recognizes by default, for example either `LINTER_DEFAULT` (as you state in the documentation) or `.markdownlint.yml`.

**Comment by Kurt-von-Laven** [comment]
Duplicate of issue #853.
