### ISSUE TITLE
The settings in the config file are not used:

### ISSUE THREAD

**Issue by danechitoaie** [megalinter/megalinter#879]
I have the following `.mega-linter.yml`

```
APPLY_FIXES: all
DEFAULT_BRANCH: develop
ENABLE: [TYPESCRIPT]
ENABLE_LINTERS: [TYPESCRIPT_PRETTIER]
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
```

Yet MegaLinter still runs with and only with `TYPESCRIPT_STANDARD`

Any idea what's going on?

**Comment by nvuillam** [comment]
Please could you share the log ? if you add `PRINT_ALL_FILES: false`, it will hide the file names so preserve your sources :)
