### ISSUE TITLE
Suggestion: Nginx linter

### ISSUE THREAD

**Issue by icetbr** [megalinter/megalinter#891]
Hi, might be a good idea to include, it catches a few but interesting problems, like ordering of location directives.

https://github.com/jhinch/nginx-linter

**Comment by nvuillam** [comment]
It seems to be a great idea, but before the repo is more widely adopted by the community, i'd prefer this linter to be a [MegaLinter plugin](https://megalinter.github.io/plugins/)

Would you be up to the task ? :)

**Comment by icetbr** [comment]
Perhaps, eventually :-) Sorry for the vagueness, I'm still trying to implement Megalinter in my projects, I've yet to find/understand how to do it. This might take a while or never happen. We use Gitlab with submodules (no monorepo), and I don't think there is a nice way to run Megalinter in all of them (we have ~50) from just one place, since there is no equivalent to a Github Apps.

Anyway, I mainly wanted to raise awareness of the existence of that repo. Perhaps if more people show their interest I'll give it a try, lets give it a while and see some upvotes here?

**Comment by nvuillam** [comment]
I think suggesting to the author is agood idea, i'll add a link to the plugin in MegaLinter doc, that may bring users to his repo, and once it's more used it will be able to be part of MegaLinter core ;)
