### ISSUE TITLE
MegaLinter v5 is up ! :)

### ISSUE THREAD

**Issue by nvuillam** [megalinter/megalinter#905]
## Mega-Linter v5 has been released :)

The creation of [megalinter organization](https://github.com/megalinter) and the migration of the repository into it will help to have a more professional way of maintaining MegaLinter, which is more and more widely used and should not remain a "one guy job".

To use it on your existing repository currently using MegaLinter v4, please run the following command at the root of your repository, it will automatically update files, so you just have to push that in a new commit and you're all set !

`npx mega-linter-runner --upgrade`

Most of functions has been tested and no major bug has been discovered after migration, but sh** happens sometimes, so **if you see something stranger than usual please post an issue** !

## Organization

@Kurt-von-Laven joined me in the [maintainers team](https://github.com/orgs/megalinter/teams/megalinter-maintainers) and can now also validate Pull Requests,

A [trusted contributors team](https://github.com/orgs/megalinter/teams/megalinter-contributors) has also been created and can directly work in the main repo without forking (that can ease CI)

If you wish to be more involved in MegaLinter project, don't hesitate to ask :) (after a few interesting PRs of course ^^)

## Updates v4 vs v5

- To upgrade your local config / CI jobs from v4 to v5, run the following command that will upgrade references to _nvuillam/mega-linter_ into _megalinter/megalinter_

    `npx mega-linter-runner --upgrade`

- Migration from github individual repo **nvuillam/mega-linter** to github organization repo **megalinter/megalinter**

- Migration from docker hub space **nvuillam** to space **megalinter**
  - Docker images are now **megalinter/megalinter** or **megalinter/megalinter-FLAVOR**

- Documentation is now hosted at <https://megalinter.github.io/>

- Version management: Now mega-linter docker images, github action and mega-linter-runner versions are aligned
  - **latest** for latest official release
  - **beta** for current content of main branch
  - **alpha** for current content of alpha branch
  - docker image, github action and mega-linter-runner can still be called with exact version number
 
- Being more inclusive: rename `master` branch into `main`

- **IGNORE_GITIGNORED_FILES** parameter default to `true`

**Comment by llaville** [comment]
@nvuillam [trusted contributors link](https://github.com/orgs/megalinter/teams/megalinter-contributors) failed to me !

**Comment by nvuillam** [comment]
@llaville check in your mails, I think you have an invitation that you must accept :)

That's strange anyway... the teams are public so they should be visible to anyone

**Comment by llaville** [comment]
@nvuillam OK link is ok now, I've accepted invitation ! Thanks :)

**Comment by nvuillam** [comment]
It seems org teams are visible only to org members ^^

But you can define yourself as public or private if you want MegaLinter org membership to be displayed on your github profile :)

**Comment by nvuillam** [comment]
There were tiny errors in PR CI validation jobs and in mega-linter-runner, should be solved now with v5.0.1 :)
