### ISSUE TITLE
Default `DEFAULT_BRANCH` is `master`

### ISSUE THREAD

**Issue by Kurt-von-Laven** [megalinter/megalinter#915]
**Describe the bug**
[The documentation](https://megalinter.github.io/configuration/#common-variables) was updated at v5 to state that `DEFAULT_BRANCH` defaults to `main`, but it still defaults to `master`.

```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch origin refs/heads/master:refs/remotes/origin/master
  stderr: 'Host key verification failed.
fatal: Could not read from remote repository.
```

**To Reproduce**

1. `cd` into a repository that uses `main` as the default branch.
2. Run Mega-Linter locally at `v5.0.4` with `VALIDATE_ALL_CODEBASE=false` without `DEFAULT_BRANCH` specified.

**Expected behavior**
I expected Mega-Linter Runner to run successfully.

**Additional context**
The documentation itself is also stale: "Warning: In new github repositories, main branch is named `main`, so you need to override this value with `main`."

**Comment by Kurt-von-Laven** [comment]
Happy to pick this one up; just want to double check whether we want to make `main` the `DEFAULT_BRANCH` or revert the documentation change.

**Comment by nvuillam** [comment]
The best of the best would be that in case there is no variable defined, we
guess automatically the branch to use by analyzing the list of remote
branches 😅

Le lun. 1 nov. 2021 à 02:21, Kurt von Laven ***@***.***> a
écrit :

**Comment by Kurt-von-Laven** [comment]
Good idea! If there is both an `origin/main` and an `origin/master`, which would you like to use?

**Comment by nvuillam** [comment]
@Kurt-von-Laven any progress on the fix ? ^^

**Comment by Kurt-von-Laven** [comment]
Should we continue respecting `DEFAULT_BRANCH` when it's present until v6?

**Comment by nvuillam** [comment]
@Kurt-von-Laven yes, else it's a breaking change ^^

**Comment by josecelano** [comment]
I've just installed it using the template from the documentation and It's using "master" branch:
https://github.com/Nautilus-Cyberneering/librarian/runs/4421786722?check_suite_focus=true

**Comment by nvuillam** [comment]
You can use npx mega-linter-runner --install so it will also initialize a `.mega-linter.yml` file at the root of your repository (wizard will ask you for your default branch)

If you prefer to do it manually, you can create a `.mega-linter.yml` file containing `DEFAULT_BRANCH: main`

**Comment by josecelano** [comment]
Thank you @nvuillam , I was following directly ["GitHub Action" section](https://megalinter.github.io/latest/installation/) from docs. I thought I did not need any other config file. I thought the assistant was only needed to generate a custom `mega-linter.yml` workflow.

**Comment by nvuillam** [comment]
@josecelano it is technically possible to define all variables in GHA workflow, but it's really clean to do it within config file `.mega-linter.yml` , and the assistant helps for that :)

**Comment by Kurt-von-Laven** [comment]
@josecelano, the change associated with this issue was merged before your workflow ran but released three days after your workflow ran in [MegaLinter v5.3.0](https://github.com/megalinter/megalinter/releases/tag/v5.3.0).

**Comment by Kurt-von-Laven** [comment]
@nvuillam, this is not time sensitive, but I want to get my thoughts down before I forget. I eventually have come to appreciate that `DEFAULT_BRANCH` is quite difficult to kill off. Consider a chain of repositories, _A_ hosted in the cloud, its direct clone _B_, and _B_'s clone _C_. If one checks out a branch other than the default branch in _B_, and then runs `git fetch` followed by MegaLinter in _C_, MegaLinter will calculate the files differing between the currently checked out branches in _B_ and _C_. I believe most people would expect and prefer that we calculate the files differing between the currently checked out branch in _C_ and the actual default branch in _A_. The trouble is, I am not sure there's a good general way to determine the default branch from a grand-clone that isn't even necessarily aware _A_ exists. Maybe we can try looking at `git config init.defaultBranch`? That will work provided that the user has updated this setting if the default branch has changed upstream. If we can't find the branch, I suppose we could fall back on asking the user to run `git config init.defaultBranch <default_branch>`. Alternatively, maybe someone has already put together a package that sorts out which Git hosting provider's API to consult for the canonical default branch for a variety of popular hosting platforms.

**Comment by nvuillam** [comment]
So... let's keep allowing users to define it within `.mega-linter.yml` ? :)

**Comment by Kurt-von-Laven** [comment]
Ha ha, yes, I think so. Well summarized.
