### ISSUE TITLE
after QuickStart: Unable to resolve action `megalinter/megalinter@v5` 

### ISSUE THREAD

**Issue by elisim** [megalinter/megalinter#918]
Thank you for the amazing project!

I ran `npx mega-linter-runner --install`, pushed the generated configs, and got:

![image](https://user-images.githubusercontent.com/17675462/139816039-4440590a-2bea-4470-a155-417a5729ad57.png)

I tried to ran `npx mega-linter-runner --upgrade` and got:

`mega-linter-runner applied 0 replacements in 0 files.`

What I did wrong?
Thank you again for the great project.

**Comment by nvuillam** [comment]
Sorry, there has been some issue with the migration to v5 🚒 

This now should be solved, please can you run again your workflow and confirm it's ok ?

`npx mega-linter-runner@latest --install`

( `--upgrade` is only if you had a previous version of MegaLinter v4 already installed )

Thanks !
