### ISSUE TITLE
Keep a changelog principles no more follows since v5.0

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#958]
**Describe the bug**
Since major version 5.0, the CHANGELOG file did not follow the [Keep a CHANGELOG](http://keepachangelog.com) principles.

**Expected behavior**
Should see the release date of each version, as it will since v4.0 

**Additional context**
Even if it's not a principle, and because releases grows a lot :
You may also consider to split CHANGELOG contents in different files, on for each major version.
Examples:
- I did it in my project https://github.com/llaville/php-compatinfo-db
- but I'm not alone, there are other projects that did it, like https://github.com/sebastianbergmann/phpunit/

Keep an `Unreleased` section at the top to track upcoming changes.  (this is another Keep A Changelog principles)

**Comment by nvuillam** [comment]
True, I don't know why I stopped putting dates :o 

+ renamed Beta into Unreleased
