### ISSUE TITLE
About PRINT_ALL_FILES feature

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#959]
I've just used the new config option `PRINT_ALL_FILES: false` and I've a question about counter to zero when a linter fails.
Is it possible to have a counter that keep count of already analysed files before the linter fails ?

See example in screenshot (look at PHPStan vs YAML prettier that is good here: 2 files analysed)

![print_all_files](https://user-images.githubusercontent.com/364342/140876050-7700d771-82e4-4396-9bf5-f6e233b7f784.png)

I use 
```
----------------------------------------------------------------------------------------------------
------------------------------------------- Mega-Linter --------------------------------------------
----------------------------------------------------------------------------------------------------
 - Image Creation Date: 2021-11-08T00:13:36Z
 - Image Revision: 63097f02
 - Image Version: beta
```

BTW, there are still an issue about error counts on PHPStan linter (but I've seen this issue in other ones)
Look at bottom of screenschot  (1 error displayed vs 3 found)

**Comment by llaville** [comment]
About my question, I think I've a beginning of answer: it's not possible when linters are in `project` mode.

This is my case for phpstan
![summary](https://user-images.githubusercontent.com/364342/140877133-da175a19-64d4-466e-9ba4-1cf59ec27754.png)

**Comment by nvuillam** [comment]
Good catch, I add a check for cli_lint_mode != project before displaying the list of files :)

**Comment by nvuillam** [comment]
about number of errors displayed, it is **1** by default when there is no cli_lint_error_count defined on the descriptor to catch the real number of errors, please make a PR with the ones for PHP if you like :)

![image](https://user-images.githubusercontent.com/17500430/140878425-8a7b8a1f-11a6-4f66-adbb-6fee0c57b558.png)

**Comment by llaville** [comment]
I've another results when all goes fines : 
`editorconfig-checker` and `phpstan` are in `project` mode and linters don't failed, but count is still zero ;-)

![print_all_files](https://user-images.githubusercontent.com/364342/140878681-57978307-b68d-4ec3-9b6f-14968454c96a.png)
