### ISSUE TITLE
Wrong error count displayed when in `project` mode

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#963]
**Describe the bug**
When linters are in `project` mode and errors occured, they cannot display the wrong issue number

**Expected behavior**
A correct errors number as in `file`

**Screenshots**

Correct issue number when linter is in `file` mode 
![psalm_ko](https://user-images.githubusercontent.com/364342/140891550-dec65963-10b2-426a-9ba4-3d0476c9e666.png)

Incorrect issue number when linter is in `project` mode 
See screenshots in https://github.com/megalinter/megalinter/issues/959

**Comment by nvuillam** [comment]
It's not related to project mode, it's related to missing `cli_lint_errors_count` and `cli_lint_regex` in descriptors :)

**Comment by llaville** [comment]
PR is on way to fix it for PHPStan and Psalm linters

**Comment by llaville** [comment]
Current results of Psalm linter in `project` mode. Should print "Found 27 error(s)" rather than 1

![psalm_error_count_project-mode](https://user-images.githubusercontent.com/364342/141644120-93364879-f376-4f84-9542-e392cf44039c.png)

**Comment by llaville** [comment]
Current results of PHPStan linter in project mode. Should print "Found 4 error(s)" rather than 1

![phpstan_errors_count_project-mode](https://user-images.githubusercontent.com/364342/141644305-504d84a6-bb44-499a-9511-fd4c069fb4d8.png)

**Comment by llaville** [comment]
PR fixed use cases in previous screenshots
