### ISSUE TITLE
Psalm does not accept `list_of_files` mode

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#964]
**Describe the bug**
Psalm v4 accept as argument one ore more files/directories to scan at once when not specified in `psalm.xml` config file.
MegaLinter v5.x did not accept `list_of_files` mode for this linter.

**To Reproduce**

1. Add `PHP_PSALM_CLI_LINT_MODE: list_of_files` in `.mega-linter.yml` config file
2. Enable PHP_PSALM linter

**Expected behavior**
A better scan performance than in default `file`mode

**Screenshots**
![psalm_listoffiles](https://user-images.githubusercontent.com/364342/140896945-1000dc23-383a-48ff-8858-78c59d8b6f64.png)

**Additional context**
Workaround is to use `project` mode for better performance with a correct `psalm.xml` config file

**Comment by nvuillam** [comment]
If PSALM can accept a list of files, you just have to define cli_lint_mode as list_of_files in the descriptor :)
Plz can u make the PR ?

**Comment by llaville** [comment]
I know. I'll plan a PR right after my main project I should finish today
