### ISSUE TITLE
Rust linting via clippy doesn't work

### ISSUE THREAD

**Issue by arush-sal** [megalinter/megalinter#975]
**Describe the bug**
When linting rust files clippy should run and return the Lint report, but instead, it simply crashes with the following error:

```
### Processed [RUST] files
- Using [clippy vERROR] https://github.com/rust-lang/rust-clippy
- Mega-Linter key: [RUST_CLIPPY]
- Rules config: identified by [clippy]
--Error detail:
error: no override and no default toolchain set

❌ Linted [RUST] files with [clippy]: Found 1 error(s) - (0.01s)
```

**To Reproduce**

1. Configure megalinter with default config as given in README for Github Actions
2. Commit a rust source code
3. Scroll down to `[RUST] files` section

**Expected behavior**
Clippy should run and simply return the lint report.

**Screenshots**
![Screenshot from 2021-11-11 22-32-19](https://user-images.githubusercontent.com/8846519/141338844-10321590-163b-4231-abb5-34c9f6eca127.png)

**Additional context**
Also, remove `dockerlint`. It doesn't seem to be working with the latest Buildkit enabled Dockerfile

**Comment by nvuillam** [comment]
Docker build test cases are working... what MegaLinter version are you using ? 
Please can you try with **beta** ?

```shell
***/tests/test_***/linters/rust_clippy_test.py::rust_clippy_test::test_failure PASSED [ 72%]
***/tests/test_***/linters/rust_clippy_test.py::rust_clippy_test::test_get_linter_help PASSED [ 72%]
***/tests/test_***/linters/rust_clippy_test.py::rust_clippy_test::test_get_linter_version PASSED [ 72%]
***/tests/test_***/linters/rust_clippy_test.py::rust_clippy_test::test_report_tap SKIPPED [ 72%]
***/tests/test_***/linters/rust_clippy_test.py::rust_clippy_test::test_success PASSED [ 73%]
```

**Comment by arush-sal** [comment]
Hi @nvuillam I am using megalinter v5. and let me try it with *beta* and `LOG_LEVEL: TRUE`

**Comment by nvuillam** [comment]
`LOG_LEVEL: DEBUG` , sorry !

**Comment by arush-sal** [comment]
@nvuillam Still no success

```
[clippy] command: ['cargo', 'clippy']
[clippy] CWD: /github/workspace
[clippy] result: 1 error: no override and no default toolchain set

Linter version command: ['/root/.cargo/bin/cargo', 'clippy', '--version']
Linter version result: 1 error: no override and no default toolchain set

Unable to get version for linter [clippy]
/root/.cargo/bin/cargo clippy --version returned output: (1) error: no override and no default toolchain set

Unable to extract version with regex re.compile('\\d+(\\.\\d+)+') from ERROR

### Processed [RUST] files
- Using [clippy vERROR] https://github.com/rust-lang/rust-clippy
- MegaLinter key: [RUST_CLIPPY]
- Rules config: identified by [clippy]
--Error detail:
error: no override and no default toolchain set

❌ Linted [RUST] files with [clippy]: Found 1 error(s) - (0.01s)
Starting new HTTPS connection (1): api.github.com:443
https://api.github.com:443 "POST /repos/<org>/<repo>/statuses/f7ac9d9f1ac2623094310e1d3c1d0cfeea07545e HTTP/1.1" 201 1570
Successfully posted Github Status for RUST with clippy
[Text Reporter] Generated TEXT report: /github/workspace/report/linters_logs/ERROR-RUST_CLIPPY.log
[prettier] command: ['prettier', '--write', '/github/workspace/.github/workflows/mega-linter.yml']
[prettier] CWD: /github/workspace
[prettier] result: 0 .github/workflows/mega-linter.yml 93ms

Popen(['git', 'diff', '--abbrev=40', '--full-index', '-M', '--raw', '-z', '--no-color'], cwd=/github/workspace, universal_newlines=False, shell=None, istream=None)
Popen(['git', 'cat-file', '--batch-check'], cwd=/github/workspace, universal_newlines=False, shell=None, istream=<valid stream>)
Linter version command: ['/node_modules/.bin/prettier', '--version']
Linter version result: 0 2.4.1
```

**Comment by arush-sal** [comment]
@nvuillam Any doc or suggestion on how can I extend the Github action for megalinter to add some specific packages and the rust toolchain?

**Comment by nvuillam** [comment]
rust-related items for Dockerfile are there -> https://github.com/megalinter/megalinter/blob/main/megalinter/descriptors/rust.megalinter-descriptor.yml

- install at rust level
- install at clippy level

If you fork then update it, then run `bash build.sh`,  then make a PR, you'll be able to see if you can solve the issue :)

Contribution instructions are [here](https://megalinter.github.io/beta/contributing/) :)

**Comment by arush-sal** [comment]
I moved the logic out of megalinter for my specific purpose. Hence marking the issue closed now.

**Comment by nvuillam** [comment]
@arush-sal does it mean that MegaLinter has a rut-related issue or not ?

**Comment by arush-sal** [comment]
@nvuillam No it is not a MegaLint concern/issue.

**Comment by nvuillam** [comment]
thanks :)

**Comment by davidBernardWefox** [comment]
I have the same issue on github runner (private runners without rust on it like on github), but I'm not able to reproduce on local desktop, when I launch the docker image (same digest than on github runner).

```txt
v5: Pulling from megalinter/megalinter-rust
Digest: sha256:1f9cda201e739d4e829899d785e1fafef85035d73564de7dbd7c750ef065a096
Status: Image is up to date for megalinter/megalinter-rust:v5
```

@arush-sal , How did you fix it ?

**Comment by davidBernardWefox** [comment]
To debug, I tried to run job (in mega-linter.yml)

```yaml
jobs:
  debug:
    runs-on: ubuntu-latest
    container:
      image: megalinter/megalinter-rust:v5
    steps:
      - name: print rust info
        run: |
          ls -al $HOME
          rustup toolchain list
          cargo version
          cargo clippy --version
```

got the 

```txt
ls -al $HOME
  rustup toolchain list
  cargo version
  cargo clippy --version
  shell: sh -e {0}
  env:
    APPLY_FIXES: none
    APPLY_FIXES_EVENT: pull_request
    APPLY_FIXES_MODE: commit
total 8
drwxr-xr-x 2 1001  121 4096 Mar  8 19:04 .
drwxr-xr-x 4 root root 4096 Mar  8 19:04 ..
no installed toolchains
error: no override and no default toolchain set
Error: Process completed with exit code 1.
```

So same behavior/bug, on local I can see folder `.cargo`and `.rustup` in `$HOME`, set to /root in the docker image

Maybe the issue is that the action, and actions are not run as root but with the user `1001` who do not have cargo and rustup setup.

**Comment by davidBernardWefox** [comment]
I was wrong, the user is root but `$HOME` is `/github/home`

```txt
echo "HOME=$HOME"
  whoami
  ls -al "$HOME"
  rustup toolchain list || true
  cargo version || true
  cargo clippy --version || true
  shell: sh -e {0}
  env:
    APPLY_FIXES: none
    APPLY_FIXES_EVENT: pull_request
    APPLY_FIXES_MODE: commit
HOME=/github/home
root
total 8
drwxr-xr-x 2 1001  121 4096 Mar  8 19:48 .
drwxr-xr-x 4 root root 4096 Mar  8 19:48 ..
no installed toolchains
error: no override and no default toolchain set
error: no override and no default toolchain set
```

**Comment by nvuillam** [comment]
@arush-sal would you have some tip to help @davidBernardWefox ? :)

**Comment by PigeonF** [comment]
You have to set the rustup override (https://rust-lang.github.io/rustup/overrides.html#overrides).

I.e. you either set `RUSTUP_TOOLCHAIN` in your workflow, or you add a `rust-toolchain.toml` to your repository.

**Comment by davidBernardWefox** [comment]
@PigeonF , thanks for the tips. It works on 1 of my repo (a dummy I created to explore workaround), but not on an other one (real project). I'll investigate deeper to understand why.

**Comment by nvuillam** [comment]
Please let me know so I can update MegaLinter the documentation, or even make a PR :)

**Comment by davidBernardWefox** [comment]
A typo caused the issue on my second project, so I confirm that adding env variable (I tried at step level), fix the issue:

```yaml
env:
  RUSTUP_TOOLCHAIN: stable
```

I can make a PR like adding at line 288 into megalinter/Dockerfile `ENV RUSTUP_TOOLCHAIN="stable"` if you like ?

Thanks

**Comment by nvuillam** [comment]
@davidBernardWefox it would be nice from you :)
But Dockerifles are automatically generated from descriptors, so your update must be done [here](https://github.com/megalinter/megalinter/blob/main/megalinter/descriptors/rust.megalinter-descriptor.yml) , then run `bash build.sh` that will regenerate the dockerfiles

**Comment by davidBernardWefox** [comment]
ok, I'll make the PR after work (from my personal github & machine)

**Comment by PigeonF** [comment]
I think it might be a better idea to set the default toolchain by running “rustup default stable” after the installation: if users have a rust-toolchain.toml in their repository, the RUSTUP_TOOLCHAIN will overwrite it, which could lead to problems (or is at least an unexpected source of error).

if i understand megalinter correctly, you should be able to add “rustup default stable” at https://github.com/megalinter/megalinter/blob/main/megalinter/descriptors/rust.megalinter-descriptor.yml#L30

**Comment by davidBernardWefox** [comment]
I'll try to test your suggestion of adding `rustup default stable`, but maybe it will not work on github because $HOME is not the same as in the container when running as github action.

**Comment by nvuillam** [comment]
It is possible to define commands to run before linting, using an overridden python class for linters

ex: https://github.com/megalinter/megalinter/blob/aa2ea617351a31c0004241273192d3487fa20dc3/megalinter/linters/TfLintLinter.py

Maybe we need something like that ?

**Comment by davidBernardWefox** [comment]
@PigeonF , 
Thanks for the workaround (you unblock me) and the guide for a better fix (finally megalinter will run `rustup default stable` before calling clippy, if file `$HOME/.rustup/settings.toml` doesn't exist)
