### ISSUE TITLE
Typo error in `.jscpd.json` 

### ISSUE THREAD

**Issue by llaville** [megalinter/megalinter#986]
**Describe the bug**
Avoid to scan `.venv` folder for contributors to speed-up execution locally

Typo error in https://github.com/megalinter/megalinter/blob/main/.jscpd.json#L8 (unexpected quote at end of folder name)

**To Reproduce**
Currently when a contributor follow [contributing guide](https://megalinter.github.io/beta/contributing/) and install a `venv` module in `.venv` folder

1. Run megalinter on source code itself
2. See screenshot

**Expected behavior**
Exclude `.venv` folder from copy/paste scan

**Screenshots**
![jscpd_ignore_files](https://user-images.githubusercontent.com/364342/141649573-65515a72-72b4-4fef-9359-974eb04f745c.png)

**Comment by llaville** [comment]
After applying fixe, it will give a better time elapsed improvement, and a nice result !

![jscpd_fixe](https://user-images.githubusercontent.com/364342/141670730-3b2254cc-6184-4757-a6ef-f189c38f9e13.png)

**Comment by llaville** [comment]
BTW, we could improve `COPYPASTE` elapsed time much more by ignoring the `site` folder that is built by contributors when running MegaLinter locally (see contributing guide)

**Comment by llaville** [comment]
@nvuillam and @Kurt-von-Laven 
It's ironic to see that COPY/PASTE did not allowed to detect issue dupplicated.
Compares the main file (now fixed)  https://github.com/megalinter/megalinter/blob/main/.jscpd.json#L8
with the TEMPLATE https://github.com/megalinter/megalinter/blob/main/TEMPLATES/.jscpd.json#L11

**Comment by Kurt-von-Laven** [comment]
@llaville, ooo, good point. Yes, I think it's safe to say the `'` should be removed in the template as well! Ha ha, MegaLinter does lend itself to some rather self-referential scenarios.

**Comment by nvuillam** [comment]
Done in #1014 :)
