### ISSUE TITLE
Update checkov version from v2.0.524 to most recent (at least v2.0.572)

### ISSUE THREAD

**Issue by dgteixeira** [megalinter/megalinter#990]
**Describe the bug**
Checkov version is out of date. The one running in mega-linter is  v2.0.524 while the most recent (as of 15th Nov 2021 12h10 Lisbon time) is 2.0.572 - Link: https://github.com/bridgecrewio/checkov/releases.

We want this upgrade because 2 issues were fixed on checkov due to GCP SA managed keys (https://github.com/bridgecrewio/checkov/pull/1884 + https://github.com/bridgecrewio/checkov/issues/1416) that we are facing when using mega-linter. Currently, we just use the .checkov.yaml file to avoid those checkov checks.

**To Reproduce**
Run mega-linter as an action with checkov enabled.

**Expected behavior**
Updated checkov rules would not trigger an error

**Screenshots**
```
### Processed [TERRAFORM] files
- Using [checkov v2.0.524] https://www.checkov.io/
```

**Comment by dgteixeira** [comment]
Since checkov is being updated on a daily basis, would it be feasible that megalinter action could trigger the upgrade if it found a more recent version? Or just trigger that update every time.

**Comment by nvuillam** [comment]
Auto-update creates a new beta version , so if you want to use latest checkov, use beta version :)

https://megalinter.github.io/beta/descriptors/terraform_checkov/

I'll also release a new official version today

**Comment by dgteixeira** [comment]
Hello @nvuillam , thanks for the fast response :)

However, I am a bit confused. Just to be sure: If I want to use the latest checkov updates, I need to use megalinter's beta version, right? Like this: `megalinter/megalinter@beta`.

Is this correct?

Thanks!

**Comment by nvuillam** [comment]
That's right :)

**Comment by dgteixeira** [comment]
@nvuillam, you're the man ❤

**Comment by nvuillam** [comment]
+31 contributors :)

FYI, checkov sometimes releases new versions several times by day ^^

**Comment by nvuillam** [comment]
v5.1.0 released successfully :)

( CTRL+F5 in doc if you still see v5.0.7 as latest version )

Don't bother CI errors, it's related to doc generation, I fixed it manually :)
